// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: product/v1/attribute.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttributeTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeTemplate) Reset() {
	*x = AttributeTemplate{}
	mi := &file_product_v1_attribute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeTemplate) ProtoMessage() {}

func (x *AttributeTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeTemplate.ProtoReflect.Descriptor instead.
func (*AttributeTemplate) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttributeTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Kind          int32                  `protobuf:"varint,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Options       []string               `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	AllowCustom   bool                   `protobuf:"varint,6,opt,name=allow_custom,json=allowCustom,proto3" json:"allow_custom,omitempty"`
	Sort          int32                  `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_product_v1_attribute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{1}
}

func (x *Attribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attribute) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attribute) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Attribute) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Attribute) GetAllowCustom() bool {
	if x != nil {
		return x.AllowCustom
	}
	return false
}

func (x *Attribute) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CreateAttributeTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttributeTemplateRequest) Reset() {
	*x = CreateAttributeTemplateRequest{}
	mi := &file_product_v1_attribute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttributeTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttributeTemplateRequest) ProtoMessage() {}

func (x *CreateAttributeTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttributeTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateAttributeTemplateRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAttributeTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateAttributeTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *AttributeTemplate     `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttributeTemplateResponse) Reset() {
	*x = CreateAttributeTemplateResponse{}
	mi := &file_product_v1_attribute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttributeTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttributeTemplateResponse) ProtoMessage() {}

func (x *CreateAttributeTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttributeTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateAttributeTemplateResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAttributeTemplateResponse) GetTemplate() *AttributeTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type DeleteAttributeTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttributeTemplateRequest) Reset() {
	*x = DeleteAttributeTemplateRequest{}
	mi := &file_product_v1_attribute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttributeTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttributeTemplateRequest) ProtoMessage() {}

func (x *DeleteAttributeTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttributeTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttributeTemplateRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAttributeTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAttributeTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttributeTemplateResponse) Reset() {
	*x = DeleteAttributeTemplateResponse{}
	mi := &file_product_v1_attribute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttributeTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttributeTemplateResponse) ProtoMessage() {}

func (x *DeleteAttributeTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttributeTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteAttributeTemplateResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{5}
}

type ListAttributeTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributeTemplatesRequest) Reset() {
	*x = ListAttributeTemplatesRequest{}
	mi := &file_product_v1_attribute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributeTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributeTemplatesRequest) ProtoMessage() {}

func (x *ListAttributeTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributeTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListAttributeTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{6}
}

type ListAttributeTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*AttributeTemplate   `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributeTemplatesResponse) Reset() {
	*x = ListAttributeTemplatesResponse{}
	mi := &file_product_v1_attribute_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributeTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributeTemplatesResponse) ProtoMessage() {}

func (x *ListAttributeTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributeTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListAttributeTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{7}
}

func (x *ListAttributeTemplatesResponse) GetTemplates() []*AttributeTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type CreateAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          int32                  `protobuf:"varint,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	AllowCustom   bool                   `protobuf:"varint,5,opt,name=allow_custom,json=allowCustom,proto3" json:"allow_custom,omitempty"`
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttributeRequest) Reset() {
	*x = CreateAttributeRequest{}
	mi := &file_product_v1_attribute_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttributeRequest) ProtoMessage() {}

func (x *CreateAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttributeRequest.ProtoReflect.Descriptor instead.
func (*CreateAttributeRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAttributeRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateAttributeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAttributeRequest) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *CreateAttributeRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateAttributeRequest) GetAllowCustom() bool {
	if x != nil {
		return x.AllowCustom
	}
	return false
}

func (x *CreateAttributeRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CreateAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     *Attribute             `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttributeResponse) Reset() {
	*x = CreateAttributeResponse{}
	mi := &file_product_v1_attribute_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttributeResponse) ProtoMessage() {}

func (x *CreateAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttributeResponse.ProtoReflect.Descriptor instead.
func (*CreateAttributeResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAttributeResponse) GetAttribute() *Attribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type UpdateAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Kind          *int32                 `protobuf:"varint,3,opt,name=kind,proto3,oneof" json:"kind,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	AllowCustom   *bool                  `protobuf:"varint,5,opt,name=allow_custom,json=allowCustom,proto3,oneof" json:"allow_custom,omitempty"`
	Sort          *int32                 `protobuf:"varint,6,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	ClearOptions  bool                   `protobuf:"varint,7,opt,name=clear_options,json=clearOptions,proto3" json:"clear_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAttributeRequest) Reset() {
	*x = UpdateAttributeRequest{}
	mi := &file_product_v1_attribute_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttributeRequest) ProtoMessage() {}

func (x *UpdateAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttributeRequest.ProtoReflect.Descriptor instead.
func (*UpdateAttributeRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAttributeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAttributeRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateAttributeRequest) GetKind() int32 {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return 0
}

func (x *UpdateAttributeRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *UpdateAttributeRequest) GetAllowCustom() bool {
	if x != nil && x.AllowCustom != nil {
		return *x.AllowCustom
	}
	return false
}

func (x *UpdateAttributeRequest) GetSort() int32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *UpdateAttributeRequest) GetClearOptions() bool {
	if x != nil {
		return x.ClearOptions
	}
	return false
}

type UpdateAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     *Attribute             `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAttributeResponse) Reset() {
	*x = UpdateAttributeResponse{}
	mi := &file_product_v1_attribute_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttributeResponse) ProtoMessage() {}

func (x *UpdateAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttributeResponse.ProtoReflect.Descriptor instead.
func (*UpdateAttributeResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateAttributeResponse) GetAttribute() *Attribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type DeleteAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttributeRequest) Reset() {
	*x = DeleteAttributeRequest{}
	mi := &file_product_v1_attribute_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttributeRequest) ProtoMessage() {}

func (x *DeleteAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttributeRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttributeRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAttributeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttributeResponse) Reset() {
	*x = DeleteAttributeResponse{}
	mi := &file_product_v1_attribute_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttributeResponse) ProtoMessage() {}

func (x *DeleteAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttributeResponse.ProtoReflect.Descriptor instead.
func (*DeleteAttributeResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{13}
}

type ListAttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributesRequest) Reset() {
	*x = ListAttributesRequest{}
	mi := &file_product_v1_attribute_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributesRequest) ProtoMessage() {}

func (x *ListAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributesRequest.ProtoReflect.Descriptor instead.
func (*ListAttributesRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{14}
}

func (x *ListAttributesRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type ListAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*Attribute           `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributesResponse) Reset() {
	*x = ListAttributesResponse{}
	mi := &file_product_v1_attribute_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributesResponse) ProtoMessage() {}

func (x *ListAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_attribute_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributesResponse.ProtoReflect.Descriptor instead.
func (*ListAttributesResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_attribute_proto_rawDescGZIP(), []int{15}
}

func (x *ListAttributesResponse) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_product_v1_attribute_proto protoreflect.FileDescriptor

const file_product_v1_attribute_proto_rawDesc = "" +
	"\n" +
	"\x1aproduct/v1/attribute.proto\x12\n" +
	"product.v1\x1a\x1cgoogle/api/annotations.proto\"7\n" +
	"\x11AttributeTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb5\x01\n" +
	"\tAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\x05R\x04kind\x12\x18\n" +
	"\aoptions\x18\x05 \x03(\tR\aoptions\x12!\n" +
	"\fallow_custom\x18\x06 \x01(\bR\vallowCustom\x12\x12\n" +
	"\x04sort\x18\a \x01(\x05R\x04sort\"4\n" +
	"\x1eCreateAttributeTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\\\n" +
	"\x1fCreateAttributeTemplateResponse\x129\n" +
	"\btemplate\x18\x01 \x01(\v2\x1d.product.v1.AttributeTemplateR\btemplate\"0\n" +
	"\x1eDeleteAttributeTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x1fDeleteAttributeTemplateResponse\"\x1f\n" +
	"\x1dListAttributeTemplatesRequest\"]\n" +
	"\x1eListAttributeTemplatesResponse\x12;\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1d.product.v1.AttributeTemplateR\ttemplates\"\xb2\x01\n" +
	"\x16CreateAttributeRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\x05R\x04kind\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12!\n" +
	"\fallow_custom\x18\x05 \x01(\bR\vallowCustom\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\"N\n" +
	"\x17CreateAttributeResponse\x123\n" +
	"\tattribute\x18\x01 \x01(\v2\x15.product.v1.AttributeR\tattribute\"\x86\x02\n" +
	"\x16UpdateAttributeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04kind\x18\x03 \x01(\x05H\x01R\x04kind\x88\x01\x01\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12&\n" +
	"\fallow_custom\x18\x05 \x01(\bH\x02R\vallowCustom\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x06 \x01(\x05H\x03R\x04sort\x88\x01\x01\x12#\n" +
	"\rclear_options\x18\a \x01(\bR\fclearOptionsB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_kindB\x0f\n" +
	"\r_allow_customB\a\n" +
	"\x05_sort\"N\n" +
	"\x17UpdateAttributeResponse\x123\n" +
	"\tattribute\x18\x01 \x01(\v2\x15.product.v1.AttributeR\tattribute\"(\n" +
	"\x16DeleteAttributeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DeleteAttributeResponse\"8\n" +
	"\x15ListAttributesRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"O\n" +
	"\x16ListAttributesResponse\x125\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x15.product.v1.AttributeR\n" +
	"attributes2\xa7\b\n" +
	"\x10AttributeService\x12\x9c\x01\n" +
	"\x17CreateAttributeTemplate\x12*.product.v1.CreateAttributeTemplateRequest\x1a+.product.v1.CreateAttributeTemplateResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/admin/attribute-templates\x12\x9e\x01\n" +
	"\x17DeleteAttributeTemplate\x12*.product.v1.DeleteAttributeTemplateRequest\x1a+.product.v1.DeleteAttributeTemplateResponse\"*\x82\xd3\xe4\x93\x02$*\"/v1/admin/attribute-templates/{id}\x12\x96\x01\n" +
	"\x16ListAttributeTemplates\x12).product.v1.ListAttributeTemplatesRequest\x1a*.product.v1.ListAttributeTemplatesResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/admin/attribute-templates\x12\x9d\x01\n" +
	"\x0fCreateAttribute\x12\".product.v1.CreateAttributeRequest\x1a#.product.v1.CreateAttributeResponse\"A\x82\xd3\xe4\x93\x02;:\x01*\"6/v1/admin/attribute-templates/{template_id}/attributes\x12\x80\x01\n" +
	"\x0fUpdateAttribute\x12\".product.v1.UpdateAttributeRequest\x1a#.product.v1.UpdateAttributeResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*2\x19/v1/admin/attributes/{id}\x12}\n" +
	"\x0fDeleteAttribute\x12\".product.v1.DeleteAttributeRequest\x1a#.product.v1.DeleteAttributeResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/admin/attributes/{id}\x12\x97\x01\n" +
	"\x0eListAttributes\x12!.product.v1.ListAttributesRequest\x1a\".product.v1.ListAttributesResponse\">\x82\xd3\xe4\x93\x028\x126/v1/admin/attribute-templates/{template_id}/attributesB1Z/github.com/tmjwjx/supermarket/api/product/v1;v1b\x06proto3"

var (
	file_product_v1_attribute_proto_rawDescOnce sync.Once
	file_product_v1_attribute_proto_rawDescData []byte
)

func file_product_v1_attribute_proto_rawDescGZIP() []byte {
	file_product_v1_attribute_proto_rawDescOnce.Do(func() {
		file_product_v1_attribute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_v1_attribute_proto_rawDesc), len(file_product_v1_attribute_proto_rawDesc)))
	})
	return file_product_v1_attribute_proto_rawDescData
}

var file_product_v1_attribute_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_product_v1_attribute_proto_goTypes = []any{
	(*AttributeTemplate)(nil),               // 0: product.v1.AttributeTemplate
	(*Attribute)(nil),                       // 1: product.v1.Attribute
	(*CreateAttributeTemplateRequest)(nil),  // 2: product.v1.CreateAttributeTemplateRequest
	(*CreateAttributeTemplateResponse)(nil), // 3: product.v1.CreateAttributeTemplateResponse
	(*DeleteAttributeTemplateRequest)(nil),  // 4: product.v1.DeleteAttributeTemplateRequest
	(*DeleteAttributeTemplateResponse)(nil), // 5: product.v1.DeleteAttributeTemplateResponse
	(*ListAttributeTemplatesRequest)(nil),   // 6: product.v1.ListAttributeTemplatesRequest
	(*ListAttributeTemplatesResponse)(nil),  // 7: product.v1.ListAttributeTemplatesResponse
	(*CreateAttributeRequest)(nil),          // 8: product.v1.CreateAttributeRequest
	(*CreateAttributeResponse)(nil),         // 9: product.v1.CreateAttributeResponse
	(*UpdateAttributeRequest)(nil),          // 10: product.v1.UpdateAttributeRequest
	(*UpdateAttributeResponse)(nil),         // 11: product.v1.UpdateAttributeResponse
	(*DeleteAttributeRequest)(nil),          // 12: product.v1.DeleteAttributeRequest
	(*DeleteAttributeResponse)(nil),         // 13: product.v1.DeleteAttributeResponse
	(*ListAttributesRequest)(nil),           // 14: product.v1.ListAttributesRequest
	(*ListAttributesResponse)(nil),          // 15: product.v1.ListAttributesResponse
}
var file_product_v1_attribute_proto_depIdxs = []int32{
	0,  // 0: product.v1.CreateAttributeTemplateResponse.template:type_name -> product.v1.AttributeTemplate
	0,  // 1: product.v1.ListAttributeTemplatesResponse.templates:type_name -> product.v1.AttributeTemplate
	1,  // 2: product.v1.CreateAttributeResponse.attribute:type_name -> product.v1.Attribute
	1,  // 3: product.v1.UpdateAttributeResponse.attribute:type_name -> product.v1.Attribute
	1,  // 4: product.v1.ListAttributesResponse.attributes:type_name -> product.v1.Attribute
	2,  // 5: product.v1.AttributeService.CreateAttributeTemplate:input_type -> product.v1.CreateAttributeTemplateRequest
	4,  // 6: product.v1.AttributeService.DeleteAttributeTemplate:input_type -> product.v1.DeleteAttributeTemplateRequest
	6,  // 7: product.v1.AttributeService.ListAttributeTemplates:input_type -> product.v1.ListAttributeTemplatesRequest
	8,  // 8: product.v1.AttributeService.CreateAttribute:input_type -> product.v1.CreateAttributeRequest
	10, // 9: product.v1.AttributeService.UpdateAttribute:input_type -> product.v1.UpdateAttributeRequest
	12, // 10: product.v1.AttributeService.DeleteAttribute:input_type -> product.v1.DeleteAttributeRequest
	14, // 11: product.v1.AttributeService.ListAttributes:input_type -> product.v1.ListAttributesRequest
	3,  // 12: product.v1.AttributeService.CreateAttributeTemplate:output_type -> product.v1.CreateAttributeTemplateResponse
	5,  // 13: product.v1.AttributeService.DeleteAttributeTemplate:output_type -> product.v1.DeleteAttributeTemplateResponse
	7,  // 14: product.v1.AttributeService.ListAttributeTemplates:output_type -> product.v1.ListAttributeTemplatesResponse
	9,  // 15: product.v1.AttributeService.CreateAttribute:output_type -> product.v1.CreateAttributeResponse
	11, // 16: product.v1.AttributeService.UpdateAttribute:output_type -> product.v1.UpdateAttributeResponse
	13, // 17: product.v1.AttributeService.DeleteAttribute:output_type -> product.v1.DeleteAttributeResponse
	15, // 18: product.v1.AttributeService.ListAttributes:output_type -> product.v1.ListAttributesResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_product_v1_attribute_proto_init() }
func file_product_v1_attribute_proto_init() {
	if File_product_v1_attribute_proto != nil {
		return
	}
	file_product_v1_attribute_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_v1_attribute_proto_rawDesc), len(file_product_v1_attribute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_v1_attribute_proto_goTypes,
		DependencyIndexes: file_product_v1_attribute_proto_depIdxs,
		MessageInfos:      file_product_v1_attribute_proto_msgTypes,
	}.Build()
	File_product_v1_attribute_proto = out.File
	file_product_v1_attribute_proto_goTypes = nil
	file_product_v1_attribute_proto_depIdxs = nil
}
