// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: product/v1/brand.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Brand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Initial       string                 `protobuf:"bytes,3,opt,name=initial,proto3" json:"initial,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Visible       bool                   `protobuf:"varint,6,opt,name=visible,proto3" json:"visible,omitempty"`
	Sort          int32                  `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Brand) Reset() {
	*x = Brand{}
	mi := &file_product_v1_brand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Brand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Brand) ProtoMessage() {}

func (x *Brand) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_brand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Brand.ProtoReflect.Descriptor instead.
func (*Brand) Descriptor() ([]byte, []int) {
	return file_product_v1_brand_proto_rawDescGZIP(), []int{0}
}

func (x *Brand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Brand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Brand) GetInitial() string {
	if x != nil {
		return x.Initial
	}
	return ""
}

func (x *Brand) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *Brand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Brand) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Brand) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CreateBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Initial       string                 `protobuf:"bytes,2,opt,name=initial,proto3" json:"initial,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Visible       bool                   `protobuf:"varint,5,opt,name=visible,proto3" json:"visible,omitempty"`
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBrandRequest) Reset() {
	*x = CreateBrandRequest{}
	mi := &file_product_v1_brand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBrandRequest) ProtoMessage() {}

func (x *CreateBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_brand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBrandRequest.ProtoReflect.Descriptor instead.
func (*CreateBrandRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_brand_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBrandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBrandRequest) GetInitial() string {
	if x != nil {
		return x.Initial
	}
	return ""
}

func (x *CreateBrandRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *CreateBrandRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBrandRequest) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *CreateBrandRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CreateBrandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         *Brand                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBrandResponse) Reset() {
	*x = CreateBrandResponse{}
	mi := &file_product_v1_brand_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBrandResponse) ProtoMessage() {}

func (x *CreateBrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_brand_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBrandResponse.ProtoReflect.Descriptor instead.
func (*CreateBrandResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_brand_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBrandResponse) GetBrand() *Brand {
	if x != nil {
		return x.Brand
	}
	return nil
}

type UpdateBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Initial       *string                `protobuf:"bytes,3,opt,name=initial,proto3,oneof" json:"initial,omitempty"`
	LogoUrl       *string                `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Visible       *bool                  `protobuf:"varint,6,opt,name=visible,proto3,oneof" json:"visible,omitempty"`
	Sort          *int32                 `protobuf:"varint,7,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBrandRequest) Reset() {
	*x = UpdateBrandRequest{}
	mi := &file_product_v1_brand_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBrandRequest) ProtoMessage() {}

func (x *UpdateBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_brand_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBrandRequest.ProtoReflect.Descriptor instead.
func (*UpdateBrandRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_brand_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBrandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBrandRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateBrandRequest) GetInitial() string {
	if x != nil && x.Initial != nil {
		return *x.Initial
	}
	return ""
}

func (x *UpdateBrandRequest) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

func (x *UpdateBrandRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateBrandRequest) GetVisible() bool {
	if x != nil && x.Visible != nil {
		return *x.Visible
	}
	return false
}

func (x *UpdateBrandRequest) GetSort() int32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

type UpdateBrandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         *Brand                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBrandResponse) Reset() {
	*x = UpdateBrandResponse{}
	mi := &file_product_v1_brand_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBrandResponse) ProtoMessage() {}

func (x *UpdateBrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_brand_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBrandResponse.ProtoReflect.Descriptor instead.
func (*UpdateBrandResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_brand_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBrandResponse) GetBrand() *Brand {
	if x != nil {
		return x.Brand
	}
	return nil
}

type DeleteBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBrandRequest) Reset() {
	*x = DeleteBrandRequest{}
	mi := &file_product_v1_brand_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBrandRequest) ProtoMessage() {}

func (x *DeleteBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_brand_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBrandRequest.ProtoReflect.Descriptor instead.
func (*DeleteBrandRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_brand_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBrandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBrandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBrandResponse) Reset() {
	*x = DeleteBrandResponse{}
	mi := &file_product_v1_brand_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBrandResponse) ProtoMessage() {}

func (x *DeleteBrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_brand_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBrandResponse.ProtoReflect.Descriptor instead.
func (*DeleteBrandResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_brand_proto_rawDescGZIP(), []int{6}
}

type ListBrandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBrandsRequest) Reset() {
	*x = ListBrandsRequest{}
	mi := &file_product_v1_brand_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBrandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrandsRequest) ProtoMessage() {}

func (x *ListBrandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_brand_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrandsRequest.ProtoReflect.Descriptor instead.
func (*ListBrandsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_brand_proto_rawDescGZIP(), []int{7}
}

type ListBrandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brands        []*Brand               `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBrandsResponse) Reset() {
	*x = ListBrandsResponse{}
	mi := &file_product_v1_brand_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBrandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBrandsResponse) ProtoMessage() {}

func (x *ListBrandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_brand_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBrandsResponse.ProtoReflect.Descriptor instead.
func (*ListBrandsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_brand_proto_rawDescGZIP(), []int{8}
}

func (x *ListBrandsResponse) GetBrands() []*Brand {
	if x != nil {
		return x.Brands
	}
	return nil
}

type AdminListBrandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListBrandsRequest) Reset() {
	*x = AdminListBrandsRequest{}
	mi := &file_product_v1_brand_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListBrandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListBrandsRequest) ProtoMessage() {}

func (x *AdminListBrandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_brand_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListBrandsRequest.ProtoReflect.Descriptor instead.
func (*AdminListBrandsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_brand_proto_rawDescGZIP(), []int{9}
}

type AdminListBrandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brands        []*Brand               `protobuf:"bytes,1,rep,name=brands,proto3" json:"brands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListBrandsResponse) Reset() {
	*x = AdminListBrandsResponse{}
	mi := &file_product_v1_brand_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListBrandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListBrandsResponse) ProtoMessage() {}

func (x *AdminListBrandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_brand_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListBrandsResponse.ProtoReflect.Descriptor instead.
func (*AdminListBrandsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_brand_proto_rawDescGZIP(), []int{10}
}

func (x *AdminListBrandsResponse) GetBrands() []*Brand {
	if x != nil {
		return x.Brands
	}
	return nil
}

var File_product_v1_brand_proto protoreflect.FileDescriptor

const file_product_v1_brand_proto_rawDesc = "" +
	"\n" +
	"\x16product/v1/brand.proto\x12\n" +
	"product.v1\x1a\x1cgoogle/api/annotations.proto\"\xb0\x01\n" +
	"\x05Brand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\ainitial\x18\x03 \x01(\tR\ainitial\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\avisible\x18\x06 \x01(\bR\avisible\x12\x12\n" +
	"\x04sort\x18\a \x01(\x05R\x04sort\"\xad\x01\n" +
	"\x12CreateBrandRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\ainitial\x18\x02 \x01(\tR\ainitial\x12\x19\n" +
	"\blogo_url\x18\x03 \x01(\tR\alogoUrl\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\avisible\x18\x05 \x01(\bR\avisible\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\">\n" +
	"\x13CreateBrandResponse\x12'\n" +
	"\x05brand\x18\x01 \x01(\v2\x11.product.v1.BrandR\x05brand\"\xa2\x02\n" +
	"\x12UpdateBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\ainitial\x18\x03 \x01(\tH\x01R\ainitial\x88\x01\x01\x12\x1e\n" +
	"\blogo_url\x18\x04 \x01(\tH\x02R\alogoUrl\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\avisible\x18\x06 \x01(\bH\x04R\avisible\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\a \x01(\x05H\x05R\x04sort\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_initialB\v\n" +
	"\t_logo_urlB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_visibleB\a\n" +
	"\x05_sort\">\n" +
	"\x13UpdateBrandResponse\x12'\n" +
	"\x05brand\x18\x01 \x01(\v2\x11.product.v1.BrandR\x05brand\"$\n" +
	"\x12DeleteBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteBrandResponse\"\x13\n" +
	"\x11ListBrandsRequest\"?\n" +
	"\x12ListBrandsResponse\x12)\n" +
	"\x06brands\x18\x01 \x03(\v2\x11.product.v1.BrandR\x06brands\"\x18\n" +
	"\x16AdminListBrandsRequest\"D\n" +
	"\x17AdminListBrandsResponse\x12)\n" +
	"\x06brands\x18\x01 \x03(\v2\x11.product.v1.BrandR\x06brands2\xb3\x04\n" +
	"\fBrandService\x12k\n" +
	"\vCreateBrand\x12\x1e.product.v1.CreateBrandRequest\x1a\x1f.product.v1.CreateBrandResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/admin/brands\x12p\n" +
	"\vUpdateBrand\x12\x1e.product.v1.UpdateBrandRequest\x1a\x1f.product.v1.UpdateBrandResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/v1/admin/brands/{id}\x12m\n" +
	"\vDeleteBrand\x12\x1e.product.v1.DeleteBrandRequest\x1a\x1f.product.v1.DeleteBrandResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/admin/brands/{id}\x12_\n" +
	"\n" +
	"ListBrands\x12\x1d.product.v1.ListBrandsRequest\x1a\x1e.product.v1.ListBrandsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/brands\x12t\n" +
	"\x0fAdminListBrands\x12\".product.v1.AdminListBrandsRequest\x1a#.product.v1.AdminListBrandsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/admin/brandsB1Z/github.com/tmjwjx/supermarket/api/product/v1;v1b\x06proto3"

var (
	file_product_v1_brand_proto_rawDescOnce sync.Once
	file_product_v1_brand_proto_rawDescData []byte
)

func file_product_v1_brand_proto_rawDescGZIP() []byte {
	file_product_v1_brand_proto_rawDescOnce.Do(func() {
		file_product_v1_brand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_v1_brand_proto_rawDesc), len(file_product_v1_brand_proto_rawDesc)))
	})
	return file_product_v1_brand_proto_rawDescData
}

var file_product_v1_brand_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_product_v1_brand_proto_goTypes = []any{
	(*Brand)(nil),                   // 0: product.v1.Brand
	(*CreateBrandRequest)(nil),      // 1: product.v1.CreateBrandRequest
	(*CreateBrandResponse)(nil),     // 2: product.v1.CreateBrandResponse
	(*UpdateBrandRequest)(nil),      // 3: product.v1.UpdateBrandRequest
	(*UpdateBrandResponse)(nil),     // 4: product.v1.UpdateBrandResponse
	(*DeleteBrandRequest)(nil),      // 5: product.v1.DeleteBrandRequest
	(*DeleteBrandResponse)(nil),     // 6: product.v1.DeleteBrandResponse
	(*ListBrandsRequest)(nil),       // 7: product.v1.ListBrandsRequest
	(*ListBrandsResponse)(nil),      // 8: product.v1.ListBrandsResponse
	(*AdminListBrandsRequest)(nil),  // 9: product.v1.AdminListBrandsRequest
	(*AdminListBrandsResponse)(nil), // 10: product.v1.AdminListBrandsResponse
}
var file_product_v1_brand_proto_depIdxs = []int32{
	0,  // 0: product.v1.CreateBrandResponse.brand:type_name -> product.v1.Brand
	0,  // 1: product.v1.UpdateBrandResponse.brand:type_name -> product.v1.Brand
	0,  // 2: product.v1.ListBrandsResponse.brands:type_name -> product.v1.Brand
	0,  // 3: product.v1.AdminListBrandsResponse.brands:type_name -> product.v1.Brand
	1,  // 4: product.v1.BrandService.CreateBrand:input_type -> product.v1.CreateBrandRequest
	3,  // 5: product.v1.BrandService.UpdateBrand:input_type -> product.v1.UpdateBrandRequest
	5,  // 6: product.v1.BrandService.DeleteBrand:input_type -> product.v1.DeleteBrandRequest
	7,  // 7: product.v1.BrandService.ListBrands:input_type -> product.v1.ListBrandsRequest
	9,  // 8: product.v1.BrandService.AdminListBrands:input_type -> product.v1.AdminListBrandsRequest
	2,  // 9: product.v1.BrandService.CreateBrand:output_type -> product.v1.CreateBrandResponse
	4,  // 10: product.v1.BrandService.UpdateBrand:output_type -> product.v1.UpdateBrandResponse
	6,  // 11: product.v1.BrandService.DeleteBrand:output_type -> product.v1.DeleteBrandResponse
	8,  // 12: product.v1.BrandService.ListBrands:output_type -> product.v1.ListBrandsResponse
	10, // 13: product.v1.BrandService.AdminListBrands:output_type -> product.v1.AdminListBrandsResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_product_v1_brand_proto_init() }
func file_product_v1_brand_proto_init() {
	if File_product_v1_brand_proto != nil {
		return
	}
	file_product_v1_brand_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_v1_brand_proto_rawDesc), len(file_product_v1_brand_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_v1_brand_proto_goTypes,
		DependencyIndexes: file_product_v1_brand_proto_depIdxs,
		MessageInfos:      file_product_v1_brand_proto_msgTypes,
	}.Build()
	File_product_v1_brand_proto = out.File
	file_product_v1_brand_proto_goTypes = nil
	file_product_v1_brand_proto_depIdxs = nil
}
