// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: product/v1/browse_history.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrowseHistoryService_ListBrowseHistories_FullMethodName  = "/product.v1.BrowseHistoryService/ListBrowseHistories"
	BrowseHistoryService_ClearBrowseHistories_FullMethodName = "/product.v1.BrowseHistoryService/ClearBrowseHistories"
)

// BrowseHistoryServiceClient is the client API for BrowseHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrowseHistoryServiceClient interface {
	ListBrowseHistories(ctx context.Context, in *ListBrowseHistoriesRequest, opts ...grpc.CallOption) (*ListBrowseHistoriesResponse, error)
	ClearBrowseHistories(ctx context.Context, in *ClearBrowseHistoriesRequest, opts ...grpc.CallOption) (*ClearBrowseHistoriesResponse, error)
}

type browseHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrowseHistoryServiceClient(cc grpc.ClientConnInterface) BrowseHistoryServiceClient {
	return &browseHistoryServiceClient{cc}
}

func (c *browseHistoryServiceClient) ListBrowseHistories(ctx context.Context, in *ListBrowseHistoriesRequest, opts ...grpc.CallOption) (*ListBrowseHistoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBrowseHistoriesResponse)
	err := c.cc.Invoke(ctx, BrowseHistoryService_ListBrowseHistories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *browseHistoryServiceClient) ClearBrowseHistories(ctx context.Context, in *ClearBrowseHistoriesRequest, opts ...grpc.CallOption) (*ClearBrowseHistoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearBrowseHistoriesResponse)
	err := c.cc.Invoke(ctx, BrowseHistoryService_ClearBrowseHistories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrowseHistoryServiceServer is the server API for BrowseHistoryService service.
// All implementations must embed UnimplementedBrowseHistoryServiceServer
// for forward compatibility.
type BrowseHistoryServiceServer interface {
	ListBrowseHistories(context.Context, *ListBrowseHistoriesRequest) (*ListBrowseHistoriesResponse, error)
	ClearBrowseHistories(context.Context, *ClearBrowseHistoriesRequest) (*ClearBrowseHistoriesResponse, error)
	mustEmbedUnimplementedBrowseHistoryServiceServer()
}

// UnimplementedBrowseHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrowseHistoryServiceServer struct{}

func (UnimplementedBrowseHistoryServiceServer) ListBrowseHistories(context.Context, *ListBrowseHistoriesRequest) (*ListBrowseHistoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBrowseHistories not implemented")
}
func (UnimplementedBrowseHistoryServiceServer) ClearBrowseHistories(context.Context, *ClearBrowseHistoriesRequest) (*ClearBrowseHistoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearBrowseHistories not implemented")
}
func (UnimplementedBrowseHistoryServiceServer) mustEmbedUnimplementedBrowseHistoryServiceServer() {}
func (UnimplementedBrowseHistoryServiceServer) testEmbeddedByValue()                              {}

// UnsafeBrowseHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrowseHistoryServiceServer will
// result in compilation errors.
type UnsafeBrowseHistoryServiceServer interface {
	mustEmbedUnimplementedBrowseHistoryServiceServer()
}

func RegisterBrowseHistoryServiceServer(s grpc.ServiceRegistrar, srv BrowseHistoryServiceServer) {
	// If the following call panics, it indicates UnimplementedBrowseHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrowseHistoryService_ServiceDesc, srv)
}

func _BrowseHistoryService_ListBrowseHistories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBrowseHistoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowseHistoryServiceServer).ListBrowseHistories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowseHistoryService_ListBrowseHistories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowseHistoryServiceServer).ListBrowseHistories(ctx, req.(*ListBrowseHistoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrowseHistoryService_ClearBrowseHistories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearBrowseHistoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrowseHistoryServiceServer).ClearBrowseHistories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrowseHistoryService_ClearBrowseHistories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrowseHistoryServiceServer).ClearBrowseHistories(ctx, req.(*ClearBrowseHistoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrowseHistoryService_ServiceDesc is the grpc.ServiceDesc for BrowseHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrowseHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.v1.BrowseHistoryService",
	HandlerType: (*BrowseHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBrowseHistories",
			Handler:    _BrowseHistoryService_ListBrowseHistories_Handler,
		},
		{
			MethodName: "ClearBrowseHistories",
			Handler:    _BrowseHistoryService_ClearBrowseHistories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product/v1/browse_history.proto",
}
