// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: product/v1/browse_history.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationBrowseHistoryServiceClearBrowseHistories = "/product.v1.BrowseHistoryService/ClearBrowseHistories"
const OperationBrowseHistoryServiceListBrowseHistories = "/product.v1.BrowseHistoryService/ListBrowseHistories"

type BrowseHistoryServiceHTTPServer interface {
	ClearBrowseHistories(context.Context, *ClearBrowseHistoriesRequest) (*ClearBrowseHistoriesResponse, error)
	ListBrowseHistories(context.Context, *ListBrowseHistoriesRequest) (*ListBrowseHistoriesResponse, error)
}

func RegisterBrowseHistoryServiceHTTPServer(s *http.Server, srv BrowseHistoryServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/browse-histories", _BrowseHistoryService_ListBrowseHistories0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/browse-histories", _BrowseHistoryService_ClearBrowseHistories0_HTTP_Handler(srv))
}

func _BrowseHistoryService_ListBrowseHistories0_HTTP_Handler(srv BrowseHistoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListBrowseHistoriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBrowseHistoryServiceListBrowseHistories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBrowseHistories(ctx, req.(*ListBrowseHistoriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBrowseHistoriesResponse)
		return ctx.Result(200, reply)
	}
}

func _BrowseHistoryService_ClearBrowseHistories0_HTTP_Handler(srv BrowseHistoryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClearBrowseHistoriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBrowseHistoryServiceClearBrowseHistories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClearBrowseHistories(ctx, req.(*ClearBrowseHistoriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClearBrowseHistoriesResponse)
		return ctx.Result(200, reply)
	}
}

type BrowseHistoryServiceHTTPClient interface {
	ClearBrowseHistories(ctx context.Context, req *ClearBrowseHistoriesRequest, opts ...http.CallOption) (rsp *ClearBrowseHistoriesResponse, err error)
	ListBrowseHistories(ctx context.Context, req *ListBrowseHistoriesRequest, opts ...http.CallOption) (rsp *ListBrowseHistoriesResponse, err error)
}

type BrowseHistoryServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewBrowseHistoryServiceHTTPClient(client *http.Client) BrowseHistoryServiceHTTPClient {
	return &BrowseHistoryServiceHTTPClientImpl{client}
}

func (c *BrowseHistoryServiceHTTPClientImpl) ClearBrowseHistories(ctx context.Context, in *ClearBrowseHistoriesRequest, opts ...http.CallOption) (*ClearBrowseHistoriesResponse, error) {
	var out ClearBrowseHistoriesResponse
	pattern := "/v1/browse-histories"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationBrowseHistoryServiceClearBrowseHistories),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BrowseHistoryServiceHTTPClientImpl) ListBrowseHistories(ctx context.Context, in *ListBrowseHistoriesRequest, opts ...http.CallOption) (*ListBrowseHistoriesResponse, error) {
	var out ListBrowseHistoriesResponse
	pattern := "/v1/browse-histories"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationBrowseHistoryServiceListBrowseHistories),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
