// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: product/v1/category.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId            string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl             string                 `protobuf:"bytes,4,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Sort                int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Visible             bool                   `protobuf:"varint,6,opt,name=visible,proto3" json:"visible,omitempty"`
	AttributeTemplateId string                 `protobuf:"bytes,7,opt,name=attribute_template_id,json=attributeTemplateId,proto3" json:"attribute_template_id,omitempty"`
	Children            []*Category            `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_product_v1_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_product_v1_category_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Category) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Category) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Category) GetAttributeTemplateId() string {
	if x != nil {
		return x.AttributeTemplateId
	}
	return ""
}

func (x *Category) GetChildren() []*Category {
	if x != nil {
		return x.Children
	}
	return nil
}

type CreateCategoryRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ParentId            string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl             string                 `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Sort                int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Visible             bool                   `protobuf:"varint,5,opt,name=visible,proto3" json:"visible,omitempty"`
	AttributeTemplateId string                 `protobuf:"bytes,6,opt,name=attribute_template_id,json=attributeTemplateId,proto3" json:"attribute_template_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_product_v1_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_category_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCategoryRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *CreateCategoryRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateCategoryRequest) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *CreateCategoryRequest) GetAttributeTemplateId() string {
	if x != nil {
		return x.AttributeTemplateId
	}
	return ""
}

type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_product_v1_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_category_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type UpdateCategoryRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	IconUrl             *string                `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3,oneof" json:"icon_url,omitempty"`
	Sort                *int32                 `protobuf:"varint,4,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Visible             *bool                  `protobuf:"varint,5,opt,name=visible,proto3,oneof" json:"visible,omitempty"`
	AttributeTemplateId *string                `protobuf:"bytes,6,opt,name=attribute_template_id,json=attributeTemplateId,proto3,oneof" json:"attribute_template_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_product_v1_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_category_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetIconUrl() string {
	if x != nil && x.IconUrl != nil {
		return *x.IconUrl
	}
	return ""
}

func (x *UpdateCategoryRequest) GetSort() int32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *UpdateCategoryRequest) GetVisible() bool {
	if x != nil && x.Visible != nil {
		return *x.Visible
	}
	return false
}

func (x *UpdateCategoryRequest) GetAttributeTemplateId() string {
	if x != nil && x.AttributeTemplateId != nil {
		return *x.AttributeTemplateId
	}
	return ""
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_product_v1_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_category_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_product_v1_category_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_category_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_category_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryResponse) Reset() {
	*x = DeleteCategoryResponse{}
	mi := &file_product_v1_category_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryResponse) ProtoMessage() {}

func (x *DeleteCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_category_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_category_proto_rawDescGZIP(), []int{6}
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_product_v1_category_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_category_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_category_proto_rawDescGZIP(), []int{7}
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_product_v1_category_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_category_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_category_proto_rawDescGZIP(), []int{8}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type AdminListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListCategoriesRequest) Reset() {
	*x = AdminListCategoriesRequest{}
	mi := &file_product_v1_category_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListCategoriesRequest) ProtoMessage() {}

func (x *AdminListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_category_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*AdminListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_category_proto_rawDescGZIP(), []int{9}
}

type AdminListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListCategoriesResponse) Reset() {
	*x = AdminListCategoriesResponse{}
	mi := &file_product_v1_category_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListCategoriesResponse) ProtoMessage() {}

func (x *AdminListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_category_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*AdminListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_category_proto_rawDescGZIP(), []int{10}
}

func (x *AdminListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_product_v1_category_proto protoreflect.FileDescriptor

const file_product_v1_category_proto_rawDesc = "" +
	"\n" +
	"\x19product/v1/category.proto\x12\n" +
	"product.v1\x1a\x1cgoogle/api/annotations.proto\"\xfa\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x04 \x01(\tR\aiconUrl\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\x12\x18\n" +
	"\avisible\x18\x06 \x01(\bR\avisible\x122\n" +
	"\x15attribute_template_id\x18\a \x01(\tR\x13attributeTemplateId\x120\n" +
	"\bchildren\x18\b \x03(\v2\x14.product.v1.CategoryR\bchildren\"\xc5\x01\n" +
	"\x15CreateCategoryRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12\x18\n" +
	"\avisible\x18\x05 \x01(\bR\avisible\x122\n" +
	"\x15attribute_template_id\x18\x06 \x01(\tR\x13attributeTemplateId\"J\n" +
	"\x16CreateCategoryResponse\x120\n" +
	"\bcategory\x18\x01 \x01(\v2\x14.product.v1.CategoryR\bcategory\"\x96\x02\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1e\n" +
	"\bicon_url\x18\x03 \x01(\tH\x01R\aiconUrl\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x04 \x01(\x05H\x02R\x04sort\x88\x01\x01\x12\x1d\n" +
	"\avisible\x18\x05 \x01(\bH\x03R\avisible\x88\x01\x01\x127\n" +
	"\x15attribute_template_id\x18\x06 \x01(\tH\x04R\x13attributeTemplateId\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_icon_urlB\a\n" +
	"\x05_sortB\n" +
	"\n" +
	"\b_visibleB\x18\n" +
	"\x16_attribute_template_id\"J\n" +
	"\x16UpdateCategoryResponse\x120\n" +
	"\bcategory\x18\x01 \x01(\v2\x14.product.v1.CategoryR\bcategory\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteCategoryResponse\"\x17\n" +
	"\x15ListCategoriesRequest\"N\n" +
	"\x16ListCategoriesResponse\x124\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x14.product.v1.CategoryR\n" +
	"categories\"\x1c\n" +
	"\x1aAdminListCategoriesRequest\"S\n" +
	"\x1bAdminListCategoriesResponse\x124\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x14.product.v1.CategoryR\n" +
	"categories2\xfe\x04\n" +
	"\x0fCategoryService\x12x\n" +
	"\x0eCreateCategory\x12!.product.v1.CreateCategoryRequest\x1a\".product.v1.CreateCategoryResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/admin/categories\x12}\n" +
	"\x0eUpdateCategory\x12!.product.v1.UpdateCategoryRequest\x1a\".product.v1.UpdateCategoryResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*2\x19/v1/admin/categories/{id}\x12z\n" +
	"\x0eDeleteCategory\x12!.product.v1.DeleteCategoryRequest\x1a\".product.v1.DeleteCategoryResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/admin/categories/{id}\x12o\n" +
	"\x0eListCategories\x12!.product.v1.ListCategoriesRequest\x1a\".product.v1.ListCategoriesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/categories\x12\x84\x01\n" +
	"\x13AdminListCategories\x12&.product.v1.AdminListCategoriesRequest\x1a'.product.v1.AdminListCategoriesResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/admin/categoriesB1Z/github.com/tmjwjx/supermarket/api/product/v1;v1b\x06proto3"

var (
	file_product_v1_category_proto_rawDescOnce sync.Once
	file_product_v1_category_proto_rawDescData []byte
)

func file_product_v1_category_proto_rawDescGZIP() []byte {
	file_product_v1_category_proto_rawDescOnce.Do(func() {
		file_product_v1_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_v1_category_proto_rawDesc), len(file_product_v1_category_proto_rawDesc)))
	})
	return file_product_v1_category_proto_rawDescData
}

var file_product_v1_category_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_product_v1_category_proto_goTypes = []any{
	(*Category)(nil),                    // 0: product.v1.Category
	(*CreateCategoryRequest)(nil),       // 1: product.v1.CreateCategoryRequest
	(*CreateCategoryResponse)(nil),      // 2: product.v1.CreateCategoryResponse
	(*UpdateCategoryRequest)(nil),       // 3: product.v1.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil),      // 4: product.v1.UpdateCategoryResponse
	(*DeleteCategoryRequest)(nil),       // 5: product.v1.DeleteCategoryRequest
	(*DeleteCategoryResponse)(nil),      // 6: product.v1.DeleteCategoryResponse
	(*ListCategoriesRequest)(nil),       // 7: product.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),      // 8: product.v1.ListCategoriesResponse
	(*AdminListCategoriesRequest)(nil),  // 9: product.v1.AdminListCategoriesRequest
	(*AdminListCategoriesResponse)(nil), // 10: product.v1.AdminListCategoriesResponse
}
var file_product_v1_category_proto_depIdxs = []int32{
	0,  // 0: product.v1.Category.children:type_name -> product.v1.Category
	0,  // 1: product.v1.CreateCategoryResponse.category:type_name -> product.v1.Category
	0,  // 2: product.v1.UpdateCategoryResponse.category:type_name -> product.v1.Category
	0,  // 3: product.v1.ListCategoriesResponse.categories:type_name -> product.v1.Category
	0,  // 4: product.v1.AdminListCategoriesResponse.categories:type_name -> product.v1.Category
	1,  // 5: product.v1.CategoryService.CreateCategory:input_type -> product.v1.CreateCategoryRequest
	3,  // 6: product.v1.CategoryService.UpdateCategory:input_type -> product.v1.UpdateCategoryRequest
	5,  // 7: product.v1.CategoryService.DeleteCategory:input_type -> product.v1.DeleteCategoryRequest
	7,  // 8: product.v1.CategoryService.ListCategories:input_type -> product.v1.ListCategoriesRequest
	9,  // 9: product.v1.CategoryService.AdminListCategories:input_type -> product.v1.AdminListCategoriesRequest
	2,  // 10: product.v1.CategoryService.CreateCategory:output_type -> product.v1.CreateCategoryResponse
	4,  // 11: product.v1.CategoryService.UpdateCategory:output_type -> product.v1.UpdateCategoryResponse
	6,  // 12: product.v1.CategoryService.DeleteCategory:output_type -> product.v1.DeleteCategoryResponse
	8,  // 13: product.v1.CategoryService.ListCategories:output_type -> product.v1.ListCategoriesResponse
	10, // 14: product.v1.CategoryService.AdminListCategories:output_type -> product.v1.AdminListCategoriesResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_product_v1_category_proto_init() }
func file_product_v1_category_proto_init() {
	if File_product_v1_category_proto != nil {
		return
	}
	file_product_v1_category_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_v1_category_proto_rawDesc), len(file_product_v1_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_v1_category_proto_goTypes,
		DependencyIndexes: file_product_v1_category_proto_depIdxs,
		MessageInfos:      file_product_v1_category_proto_msgTypes,
	}.Build()
	File_product_v1_category_proto = out.File
	file_product_v1_category_proto_goTypes = nil
	file_product_v1_category_proto_depIdxs = nil
}
