// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: product/v1/product.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationProductServiceAdminGetProduct = "/product.v1.ProductService/AdminGetProduct"
const OperationProductServiceAdminListProducts = "/product.v1.ProductService/AdminListProducts"
const OperationProductServiceApproveProduct = "/product.v1.ProductService/ApproveProduct"
const OperationProductServiceBatchPublishProducts = "/product.v1.ProductService/BatchPublishProducts"
const OperationProductServiceBatchUnpublishProducts = "/product.v1.ProductService/BatchUnpublishProducts"
const OperationProductServiceCreateProduct = "/product.v1.ProductService/CreateProduct"
const OperationProductServiceDeleteProduct = "/product.v1.ProductService/DeleteProduct"
const OperationProductServiceGetProduct = "/product.v1.ProductService/GetProduct"
const OperationProductServiceGetProductDetail = "/product.v1.ProductService/GetProductDetail"
const OperationProductServiceListDeletedProducts = "/product.v1.ProductService/ListDeletedProducts"
const OperationProductServiceListProductAudits = "/product.v1.ProductService/ListProductAudits"
const OperationProductServiceListProductLogs = "/product.v1.ProductService/ListProductLogs"
const OperationProductServiceListProducts = "/product.v1.ProductService/ListProducts"
const OperationProductServicePublishProduct = "/product.v1.ProductService/PublishProduct"
const OperationProductServicePurgeProduct = "/product.v1.ProductService/PurgeProduct"
const OperationProductServiceRejectProduct = "/product.v1.ProductService/RejectProduct"
const OperationProductServiceRestoreProduct = "/product.v1.ProductService/RestoreProduct"
const OperationProductServiceSearchProducts = "/product.v1.ProductService/SearchProducts"
const OperationProductServiceSubmitProduct = "/product.v1.ProductService/SubmitProduct"
const OperationProductServiceUnpublishProduct = "/product.v1.ProductService/UnpublishProduct"
const OperationProductServiceUpdateProduct = "/product.v1.ProductService/UpdateProduct"
const OperationProductServiceUpdateSkuPrice = "/product.v1.ProductService/UpdateSkuPrice"

type ProductServiceHTTPServer interface {
	AdminGetProduct(context.Context, *AdminGetProductRequest) (*AdminGetProductResponse, error)
	AdminListProducts(context.Context, *AdminListProductsRequest) (*AdminListProductsResponse, error)
	ApproveProduct(context.Context, *ApproveProductRequest) (*ApproveProductResponse, error)
	BatchPublishProducts(context.Context, *BatchPublishProductsRequest) (*BatchPublishProductsResponse, error)
	BatchUnpublishProducts(context.Context, *BatchUnpublishProductsRequest) (*BatchUnpublishProductsResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	GetProductDetail(context.Context, *GetProductDetailRequest) (*GetProductDetailResponse, error)
	ListDeletedProducts(context.Context, *ListDeletedProductsRequest) (*ListDeletedProductsResponse, error)
	ListProductAudits(context.Context, *ListProductAuditsRequest) (*ListProductAuditsResponse, error)
	ListProductLogs(context.Context, *ListProductLogsRequest) (*ListProductLogsResponse, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	PublishProduct(context.Context, *PublishProductRequest) (*PublishProductResponse, error)
	PurgeProduct(context.Context, *PurgeProductRequest) (*PurgeProductResponse, error)
	RejectProduct(context.Context, *RejectProductRequest) (*RejectProductResponse, error)
	RestoreProduct(context.Context, *RestoreProductRequest) (*RestoreProductResponse, error)
	SearchProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error)
	SubmitProduct(context.Context, *SubmitProductRequest) (*SubmitProductResponse, error)
	UnpublishProduct(context.Context, *UnpublishProductRequest) (*UnpublishProductResponse, error)
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	UpdateSkuPrice(context.Context, *UpdateSkuPriceRequest) (*UpdateSkuPriceResponse, error)
}

func RegisterProductServiceHTTPServer(s *http.Server, srv ProductServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/admin/products", _ProductService_CreateProduct0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/products/{id}:publish", _ProductService_PublishProduct0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/products/{id}:unpublish", _ProductService_UnpublishProduct0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/products", _ProductService_ListProducts0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/products/{id}", _ProductService_GetProduct0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/products/{id}/detail", _ProductService_GetProductDetail0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/products:search", _ProductService_SearchProducts0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/products", _ProductService_AdminListProducts0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/products/{id}", _ProductService_AdminGetProduct0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/products/{id}:submit", _ProductService_SubmitProduct0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/products/{id}:approve", _ProductService_ApproveProduct0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/products/{id}:reject", _ProductService_RejectProduct0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/products/{id}", _ProductService_DeleteProduct0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/products/{id}:restore", _ProductService_RestoreProduct0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/products/{id}:purge", _ProductService_PurgeProduct0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/products:batchPublish", _ProductService_BatchPublishProducts0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/products:batchUnpublish", _ProductService_BatchUnpublishProducts0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/products/{product_id}/skus/{sku_id}:price", _ProductService_UpdateSkuPrice0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/products:deleted", _ProductService_ListDeletedProducts0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/admin/products/{id}", _ProductService_UpdateProduct0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/products/{product_id}/audits", _ProductService_ListProductAudits0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/product-logs", _ProductService_ListProductLogs0_HTTP_Handler(srv))
}

func _ProductService_CreateProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceCreateProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProduct(ctx, req.(*CreateProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_PublishProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PublishProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServicePublishProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishProduct(ctx, req.(*PublishProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PublishProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_UnpublishProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnpublishProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceUnpublishProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnpublishProduct(ctx, req.(*UnpublishProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UnpublishProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_ListProducts0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceListProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProducts(ctx, req.(*ListProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_GetProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceGetProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProduct(ctx, req.(*GetProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_GetProductDetail0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProductDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceGetProductDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProductDetail(ctx, req.(*GetProductDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProductDetailResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_SearchProducts0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceSearchProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchProducts(ctx, req.(*SearchProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchProductsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_AdminListProducts0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminListProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceAdminListProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminListProducts(ctx, req.(*AdminListProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminListProductsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_AdminGetProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminGetProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceAdminGetProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminGetProduct(ctx, req.(*AdminGetProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminGetProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_SubmitProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceSubmitProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitProduct(ctx, req.(*SubmitProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_ApproveProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApproveProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceApproveProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApproveProduct(ctx, req.(*ApproveProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApproveProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_RejectProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RejectProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceRejectProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RejectProduct(ctx, req.(*RejectProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RejectProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_DeleteProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceDeleteProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProduct(ctx, req.(*DeleteProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_RestoreProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RestoreProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceRestoreProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RestoreProduct(ctx, req.(*RestoreProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RestoreProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_PurgeProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PurgeProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServicePurgeProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PurgeProduct(ctx, req.(*PurgeProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PurgeProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_BatchPublishProducts0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchPublishProductsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceBatchPublishProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchPublishProducts(ctx, req.(*BatchPublishProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchPublishProductsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_BatchUnpublishProducts0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchUnpublishProductsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceBatchUnpublishProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchUnpublishProducts(ctx, req.(*BatchUnpublishProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchUnpublishProductsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_UpdateSkuPrice0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSkuPriceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceUpdateSkuPrice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSkuPrice(ctx, req.(*UpdateSkuPriceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSkuPriceResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_ListDeletedProducts0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDeletedProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceListDeletedProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDeletedProducts(ctx, req.(*ListDeletedProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDeletedProductsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_UpdateProduct0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProductRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceUpdateProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProduct(ctx, req.(*UpdateProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateProductResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_ListProductAudits0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProductAuditsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceListProductAudits)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProductAudits(ctx, req.(*ListProductAuditsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductAuditsResponse)
		return ctx.Result(200, reply)
	}
}

func _ProductService_ListProductLogs0_HTTP_Handler(srv ProductServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProductLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductServiceListProductLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProductLogs(ctx, req.(*ListProductLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductLogsResponse)
		return ctx.Result(200, reply)
	}
}

type ProductServiceHTTPClient interface {
	AdminGetProduct(ctx context.Context, req *AdminGetProductRequest, opts ...http.CallOption) (rsp *AdminGetProductResponse, err error)
	AdminListProducts(ctx context.Context, req *AdminListProductsRequest, opts ...http.CallOption) (rsp *AdminListProductsResponse, err error)
	ApproveProduct(ctx context.Context, req *ApproveProductRequest, opts ...http.CallOption) (rsp *ApproveProductResponse, err error)
	BatchPublishProducts(ctx context.Context, req *BatchPublishProductsRequest, opts ...http.CallOption) (rsp *BatchPublishProductsResponse, err error)
	BatchUnpublishProducts(ctx context.Context, req *BatchUnpublishProductsRequest, opts ...http.CallOption) (rsp *BatchUnpublishProductsResponse, err error)
	CreateProduct(ctx context.Context, req *CreateProductRequest, opts ...http.CallOption) (rsp *CreateProductResponse, err error)
	DeleteProduct(ctx context.Context, req *DeleteProductRequest, opts ...http.CallOption) (rsp *DeleteProductResponse, err error)
	GetProduct(ctx context.Context, req *GetProductRequest, opts ...http.CallOption) (rsp *GetProductResponse, err error)
	GetProductDetail(ctx context.Context, req *GetProductDetailRequest, opts ...http.CallOption) (rsp *GetProductDetailResponse, err error)
	ListDeletedProducts(ctx context.Context, req *ListDeletedProductsRequest, opts ...http.CallOption) (rsp *ListDeletedProductsResponse, err error)
	ListProductAudits(ctx context.Context, req *ListProductAuditsRequest, opts ...http.CallOption) (rsp *ListProductAuditsResponse, err error)
	ListProductLogs(ctx context.Context, req *ListProductLogsRequest, opts ...http.CallOption) (rsp *ListProductLogsResponse, err error)
	ListProducts(ctx context.Context, req *ListProductsRequest, opts ...http.CallOption) (rsp *ListProductsResponse, err error)
	PublishProduct(ctx context.Context, req *PublishProductRequest, opts ...http.CallOption) (rsp *PublishProductResponse, err error)
	PurgeProduct(ctx context.Context, req *PurgeProductRequest, opts ...http.CallOption) (rsp *PurgeProductResponse, err error)
	RejectProduct(ctx context.Context, req *RejectProductRequest, opts ...http.CallOption) (rsp *RejectProductResponse, err error)
	RestoreProduct(ctx context.Context, req *RestoreProductRequest, opts ...http.CallOption) (rsp *RestoreProductResponse, err error)
	SearchProducts(ctx context.Context, req *SearchProductsRequest, opts ...http.CallOption) (rsp *SearchProductsResponse, err error)
	SubmitProduct(ctx context.Context, req *SubmitProductRequest, opts ...http.CallOption) (rsp *SubmitProductResponse, err error)
	UnpublishProduct(ctx context.Context, req *UnpublishProductRequest, opts ...http.CallOption) (rsp *UnpublishProductResponse, err error)
	UpdateProduct(ctx context.Context, req *UpdateProductRequest, opts ...http.CallOption) (rsp *UpdateProductResponse, err error)
	UpdateSkuPrice(ctx context.Context, req *UpdateSkuPriceRequest, opts ...http.CallOption) (rsp *UpdateSkuPriceResponse, err error)
}

type ProductServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProductServiceHTTPClient(client *http.Client) ProductServiceHTTPClient {
	return &ProductServiceHTTPClientImpl{client}
}

func (c *ProductServiceHTTPClientImpl) AdminGetProduct(ctx context.Context, in *AdminGetProductRequest, opts ...http.CallOption) (*AdminGetProductResponse, error) {
	var out AdminGetProductResponse
	pattern := "/v1/admin/products/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProductServiceAdminGetProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) AdminListProducts(ctx context.Context, in *AdminListProductsRequest, opts ...http.CallOption) (*AdminListProductsResponse, error) {
	var out AdminListProductsResponse
	pattern := "/v1/admin/products"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProductServiceAdminListProducts),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) ApproveProduct(ctx context.Context, in *ApproveProductRequest, opts ...http.CallOption) (*ApproveProductResponse, error) {
	var out ApproveProductResponse
	pattern := "/v1/admin/products/{id}:approve"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServiceApproveProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) BatchPublishProducts(ctx context.Context, in *BatchPublishProductsRequest, opts ...http.CallOption) (*BatchPublishProductsResponse, error) {
	var out BatchPublishProductsResponse
	pattern := "/v1/admin/products:batchPublish"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServiceBatchPublishProducts),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) BatchUnpublishProducts(ctx context.Context, in *BatchUnpublishProductsRequest, opts ...http.CallOption) (*BatchUnpublishProductsResponse, error) {
	var out BatchUnpublishProductsResponse
	pattern := "/v1/admin/products:batchUnpublish"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServiceBatchUnpublishProducts),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...http.CallOption) (*CreateProductResponse, error) {
	var out CreateProductResponse
	pattern := "/v1/admin/products"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServiceCreateProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...http.CallOption) (*DeleteProductResponse, error) {
	var out DeleteProductResponse
	pattern := "/v1/admin/products/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProductServiceDeleteProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) GetProduct(ctx context.Context, in *GetProductRequest, opts ...http.CallOption) (*GetProductResponse, error) {
	var out GetProductResponse
	pattern := "/v1/products/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProductServiceGetProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) GetProductDetail(ctx context.Context, in *GetProductDetailRequest, opts ...http.CallOption) (*GetProductDetailResponse, error) {
	var out GetProductDetailResponse
	pattern := "/v1/products/{id}/detail"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProductServiceGetProductDetail),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) ListDeletedProducts(ctx context.Context, in *ListDeletedProductsRequest, opts ...http.CallOption) (*ListDeletedProductsResponse, error) {
	var out ListDeletedProductsResponse
	pattern := "/v1/admin/products:deleted"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProductServiceListDeletedProducts),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) ListProductAudits(ctx context.Context, in *ListProductAuditsRequest, opts ...http.CallOption) (*ListProductAuditsResponse, error) {
	var out ListProductAuditsResponse
	pattern := "/v1/admin/products/{product_id}/audits"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProductServiceListProductAudits),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) ListProductLogs(ctx context.Context, in *ListProductLogsRequest, opts ...http.CallOption) (*ListProductLogsResponse, error) {
	var out ListProductLogsResponse
	pattern := "/v1/admin/product-logs"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProductServiceListProductLogs),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...http.CallOption) (*ListProductsResponse, error) {
	var out ListProductsResponse
	pattern := "/v1/products"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProductServiceListProducts),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) PublishProduct(ctx context.Context, in *PublishProductRequest, opts ...http.CallOption) (*PublishProductResponse, error) {
	var out PublishProductResponse
	pattern := "/v1/admin/products/{id}:publish"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServicePublishProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) PurgeProduct(ctx context.Context, in *PurgeProductRequest, opts ...http.CallOption) (*PurgeProductResponse, error) {
	var out PurgeProductResponse
	pattern := "/v1/admin/products/{id}:purge"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServicePurgeProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) RejectProduct(ctx context.Context, in *RejectProductRequest, opts ...http.CallOption) (*RejectProductResponse, error) {
	var out RejectProductResponse
	pattern := "/v1/admin/products/{id}:reject"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServiceRejectProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) RestoreProduct(ctx context.Context, in *RestoreProductRequest, opts ...http.CallOption) (*RestoreProductResponse, error) {
	var out RestoreProductResponse
	pattern := "/v1/admin/products/{id}:restore"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServiceRestoreProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...http.CallOption) (*SearchProductsResponse, error) {
	var out SearchProductsResponse
	pattern := "/v1/products:search"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProductServiceSearchProducts),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) SubmitProduct(ctx context.Context, in *SubmitProductRequest, opts ...http.CallOption) (*SubmitProductResponse, error) {
	var out SubmitProductResponse
	pattern := "/v1/admin/products/{id}:submit"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServiceSubmitProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) UnpublishProduct(ctx context.Context, in *UnpublishProductRequest, opts ...http.CallOption) (*UnpublishProductResponse, error) {
	var out UnpublishProductResponse
	pattern := "/v1/admin/products/{id}:unpublish"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServiceUnpublishProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...http.CallOption) (*UpdateProductResponse, error) {
	var out UpdateProductResponse
	pattern := "/v1/admin/products/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServiceUpdateProduct),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProductServiceHTTPClientImpl) UpdateSkuPrice(ctx context.Context, in *UpdateSkuPriceRequest, opts ...http.CallOption) (*UpdateSkuPriceResponse, error) {
	var out UpdateSkuPriceResponse
	pattern := "/v1/admin/products/{product_id}/skus/{sku_id}:price"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProductServiceUpdateSkuPrice),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
