// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: product/v1/recommendation.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationRecommendationServiceAdminListRecommendations = "/product.v1.RecommendationService/AdminListRecommendations"
const OperationRecommendationServiceCreateRecommendation = "/product.v1.RecommendationService/CreateRecommendation"
const OperationRecommendationServiceDeleteRecommendation = "/product.v1.RecommendationService/DeleteRecommendation"
const OperationRecommendationServiceListRecommendations = "/product.v1.RecommendationService/ListRecommendations"
const OperationRecommendationServiceUpdateRecommendation = "/product.v1.RecommendationService/UpdateRecommendation"

type RecommendationServiceHTTPServer interface {
	AdminListRecommendations(context.Context, *AdminListRecommendationsRequest) (*AdminListRecommendationsResponse, error)
	CreateRecommendation(context.Context, *CreateRecommendationRequest) (*CreateRecommendationResponse, error)
	DeleteRecommendation(context.Context, *DeleteRecommendationRequest) (*DeleteRecommendationResponse, error)
	ListRecommendations(context.Context, *ListRecommendationsRequest) (*ListRecommendationsResponse, error)
	UpdateRecommendation(context.Context, *UpdateRecommendationRequest) (*UpdateRecommendationResponse, error)
}

func RegisterRecommendationServiceHTTPServer(s *http.Server, srv RecommendationServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/admin/recommendations", _RecommendationService_CreateRecommendation0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/recommendations", _RecommendationService_ListRecommendations0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/recommendations", _RecommendationService_AdminListRecommendations0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/admin/recommendations/{id}", _RecommendationService_UpdateRecommendation0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin/recommendations/{id}", _RecommendationService_DeleteRecommendation0_HTTP_Handler(srv))
}

func _RecommendationService_CreateRecommendation0_HTTP_Handler(srv RecommendationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRecommendationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRecommendationServiceCreateRecommendation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRecommendation(ctx, req.(*CreateRecommendationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateRecommendationResponse)
		return ctx.Result(200, reply)
	}
}

func _RecommendationService_ListRecommendations0_HTTP_Handler(srv RecommendationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRecommendationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRecommendationServiceListRecommendations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRecommendations(ctx, req.(*ListRecommendationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRecommendationsResponse)
		return ctx.Result(200, reply)
	}
}

func _RecommendationService_AdminListRecommendations0_HTTP_Handler(srv RecommendationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminListRecommendationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRecommendationServiceAdminListRecommendations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminListRecommendations(ctx, req.(*AdminListRecommendationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminListRecommendationsResponse)
		return ctx.Result(200, reply)
	}
}

func _RecommendationService_UpdateRecommendation0_HTTP_Handler(srv RecommendationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateRecommendationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRecommendationServiceUpdateRecommendation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateRecommendation(ctx, req.(*UpdateRecommendationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateRecommendationResponse)
		return ctx.Result(200, reply)
	}
}

func _RecommendationService_DeleteRecommendation0_HTTP_Handler(srv RecommendationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRecommendationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRecommendationServiceDeleteRecommendation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRecommendation(ctx, req.(*DeleteRecommendationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteRecommendationResponse)
		return ctx.Result(200, reply)
	}
}

type RecommendationServiceHTTPClient interface {
	AdminListRecommendations(ctx context.Context, req *AdminListRecommendationsRequest, opts ...http.CallOption) (rsp *AdminListRecommendationsResponse, err error)
	CreateRecommendation(ctx context.Context, req *CreateRecommendationRequest, opts ...http.CallOption) (rsp *CreateRecommendationResponse, err error)
	DeleteRecommendation(ctx context.Context, req *DeleteRecommendationRequest, opts ...http.CallOption) (rsp *DeleteRecommendationResponse, err error)
	ListRecommendations(ctx context.Context, req *ListRecommendationsRequest, opts ...http.CallOption) (rsp *ListRecommendationsResponse, err error)
	UpdateRecommendation(ctx context.Context, req *UpdateRecommendationRequest, opts ...http.CallOption) (rsp *UpdateRecommendationResponse, err error)
}

type RecommendationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRecommendationServiceHTTPClient(client *http.Client) RecommendationServiceHTTPClient {
	return &RecommendationServiceHTTPClientImpl{client}
}

func (c *RecommendationServiceHTTPClientImpl) AdminListRecommendations(ctx context.Context, in *AdminListRecommendationsRequest, opts ...http.CallOption) (*AdminListRecommendationsResponse, error) {
	var out AdminListRecommendationsResponse
	pattern := "/v1/admin/recommendations"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRecommendationServiceAdminListRecommendations),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RecommendationServiceHTTPClientImpl) CreateRecommendation(ctx context.Context, in *CreateRecommendationRequest, opts ...http.CallOption) (*CreateRecommendationResponse, error) {
	var out CreateRecommendationResponse
	pattern := "/v1/admin/recommendations"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationRecommendationServiceCreateRecommendation),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RecommendationServiceHTTPClientImpl) DeleteRecommendation(ctx context.Context, in *DeleteRecommendationRequest, opts ...http.CallOption) (*DeleteRecommendationResponse, error) {
	var out DeleteRecommendationResponse
	pattern := "/v1/admin/recommendations/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRecommendationServiceDeleteRecommendation),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RecommendationServiceHTTPClientImpl) ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...http.CallOption) (*ListRecommendationsResponse, error) {
	var out ListRecommendationsResponse
	pattern := "/v1/recommendations"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRecommendationServiceListRecommendations),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *RecommendationServiceHTTPClientImpl) UpdateRecommendation(ctx context.Context, in *UpdateRecommendationRequest, opts ...http.CallOption) (*UpdateRecommendationResponse, error) {
	var out UpdateRecommendationResponse
	pattern := "/v1/admin/recommendations/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationRecommendationServiceUpdateRecommendation),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
