// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: product/v1/recommendation.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Recommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slot          string                 `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Product       *ProductCard           `protobuf:"bytes,5,opt,name=product,proto3" json:"product,omitempty"`
	StartAtUnix   int64                  `protobuf:"varint,6,opt,name=start_at_unix,json=startAtUnix,proto3" json:"start_at_unix,omitempty"`
	EndAtUnix     int64                  `protobuf:"varint,7,opt,name=end_at_unix,json=endAtUnix,proto3" json:"end_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_product_v1_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_product_v1_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *Recommendation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recommendation) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *Recommendation) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Recommendation) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Recommendation) GetProduct() *ProductCard {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *Recommendation) GetStartAtUnix() int64 {
	if x != nil {
		return x.StartAtUnix
	}
	return 0
}

func (x *Recommendation) GetEndAtUnix() int64 {
	if x != nil {
		return x.EndAtUnix
	}
	return 0
}

type CreateRecommendationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	StartAtUnix   int64                  `protobuf:"varint,4,opt,name=start_at_unix,json=startAtUnix,proto3" json:"start_at_unix,omitempty"`
	EndAtUnix     int64                  `protobuf:"varint,5,opt,name=end_at_unix,json=endAtUnix,proto3" json:"end_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecommendationRequest) Reset() {
	*x = CreateRecommendationRequest{}
	mi := &file_product_v1_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecommendationRequest) ProtoMessage() {}

func (x *CreateRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecommendationRequest.ProtoReflect.Descriptor instead.
func (*CreateRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRecommendationRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *CreateRecommendationRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateRecommendationRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateRecommendationRequest) GetStartAtUnix() int64 {
	if x != nil {
		return x.StartAtUnix
	}
	return 0
}

func (x *CreateRecommendationRequest) GetEndAtUnix() int64 {
	if x != nil {
		return x.EndAtUnix
	}
	return 0
}

type CreateRecommendationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Recommendation *Recommendation        `protobuf:"bytes,1,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRecommendationResponse) Reset() {
	*x = CreateRecommendationResponse{}
	mi := &file_product_v1_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecommendationResponse) ProtoMessage() {}

func (x *CreateRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecommendationResponse.ProtoReflect.Descriptor instead.
func (*CreateRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRecommendationResponse) GetRecommendation() *Recommendation {
	if x != nil {
		return x.Recommendation
	}
	return nil
}

type ListRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendationsRequest) Reset() {
	*x = ListRecommendationsRequest{}
	mi := &file_product_v1_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendationsRequest) ProtoMessage() {}

func (x *ListRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*ListRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *ListRecommendationsRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type ListRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*Recommendation      `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListRecommendationsResponse) Reset() {
	*x = ListRecommendationsResponse{}
	mi := &file_product_v1_recommendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendationsResponse) ProtoMessage() {}

func (x *ListRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_recommendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*ListRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_recommendation_proto_rawDescGZIP(), []int{4}
}

func (x *ListRecommendationsResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type AdminListRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          string                 `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListRecommendationsRequest) Reset() {
	*x = AdminListRecommendationsRequest{}
	mi := &file_product_v1_recommendation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListRecommendationsRequest) ProtoMessage() {}

func (x *AdminListRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_recommendation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*AdminListRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_recommendation_proto_rawDescGZIP(), []int{5}
}

func (x *AdminListRecommendationsRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type AdminListRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*Recommendation      `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminListRecommendationsResponse) Reset() {
	*x = AdminListRecommendationsResponse{}
	mi := &file_product_v1_recommendation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListRecommendationsResponse) ProtoMessage() {}

func (x *AdminListRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_recommendation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*AdminListRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_recommendation_proto_rawDescGZIP(), []int{6}
}

func (x *AdminListRecommendationsResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type UpdateRecommendationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slot          *string                `protobuf:"bytes,2,opt,name=slot,proto3,oneof" json:"slot,omitempty"`
	ProductId     *string                `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	Sort          *int32                 `protobuf:"varint,4,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	StartAtUnix   *int64                 `protobuf:"varint,5,opt,name=start_at_unix,json=startAtUnix,proto3,oneof" json:"start_at_unix,omitempty"`
	EndAtUnix     *int64                 `protobuf:"varint,6,opt,name=end_at_unix,json=endAtUnix,proto3,oneof" json:"end_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecommendationRequest) Reset() {
	*x = UpdateRecommendationRequest{}
	mi := &file_product_v1_recommendation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecommendationRequest) ProtoMessage() {}

func (x *UpdateRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_recommendation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecommendationRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_recommendation_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRecommendationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRecommendationRequest) GetSlot() string {
	if x != nil && x.Slot != nil {
		return *x.Slot
	}
	return ""
}

func (x *UpdateRecommendationRequest) GetProductId() string {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return ""
}

func (x *UpdateRecommendationRequest) GetSort() int32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *UpdateRecommendationRequest) GetStartAtUnix() int64 {
	if x != nil && x.StartAtUnix != nil {
		return *x.StartAtUnix
	}
	return 0
}

func (x *UpdateRecommendationRequest) GetEndAtUnix() int64 {
	if x != nil && x.EndAtUnix != nil {
		return *x.EndAtUnix
	}
	return 0
}

type UpdateRecommendationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Recommendation *Recommendation        `protobuf:"bytes,1,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRecommendationResponse) Reset() {
	*x = UpdateRecommendationResponse{}
	mi := &file_product_v1_recommendation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecommendationResponse) ProtoMessage() {}

func (x *UpdateRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_recommendation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecommendationResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_recommendation_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRecommendationResponse) GetRecommendation() *Recommendation {
	if x != nil {
		return x.Recommendation
	}
	return nil
}

type DeleteRecommendationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecommendationRequest) Reset() {
	*x = DeleteRecommendationRequest{}
	mi := &file_product_v1_recommendation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecommendationRequest) ProtoMessage() {}

func (x *DeleteRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_recommendation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecommendationRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_recommendation_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRecommendationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRecommendationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecommendationResponse) Reset() {
	*x = DeleteRecommendationResponse{}
	mi := &file_product_v1_recommendation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecommendationResponse) ProtoMessage() {}

func (x *DeleteRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_recommendation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecommendationResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_recommendation_proto_rawDescGZIP(), []int{10}
}

var File_product_v1_recommendation_proto protoreflect.FileDescriptor

const file_product_v1_recommendation_proto_rawDesc = "" +
	"\n" +
	"\x1fproduct/v1/recommendation.proto\x12\n" +
	"product.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x16product/v1/types.proto\"\xde\x01\n" +
	"\x0eRecommendation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\tR\x04slot\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x121\n" +
	"\aproduct\x18\x05 \x01(\v2\x17.product.v1.ProductCardR\aproduct\x12\"\n" +
	"\rstart_at_unix\x18\x06 \x01(\x03R\vstartAtUnix\x12\x1e\n" +
	"\vend_at_unix\x18\a \x01(\x03R\tendAtUnix\"\xa8\x01\n" +
	"\x1bCreateRecommendationRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\x12\"\n" +
	"\rstart_at_unix\x18\x04 \x01(\x03R\vstartAtUnix\x12\x1e\n" +
	"\vend_at_unix\x18\x05 \x01(\x03R\tendAtUnix\"b\n" +
	"\x1cCreateRecommendationResponse\x12B\n" +
	"\x0erecommendation\x18\x01 \x01(\v2\x1a.product.v1.RecommendationR\x0erecommendation\"0\n" +
	"\x1aListRecommendationsRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\"c\n" +
	"\x1bListRecommendationsResponse\x12D\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x1a.product.v1.RecommendationR\x0frecommendations\"5\n" +
	"\x1fAdminListRecommendationsRequest\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\tR\x04slot\"h\n" +
	" AdminListRecommendationsResponse\x12D\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x1a.product.v1.RecommendationR\x0frecommendations\"\x94\x02\n" +
	"\x1bUpdateRecommendationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04slot\x18\x02 \x01(\tH\x00R\x04slot\x88\x01\x01\x12\"\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tH\x01R\tproductId\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x04 \x01(\x05H\x02R\x04sort\x88\x01\x01\x12'\n" +
	"\rstart_at_unix\x18\x05 \x01(\x03H\x03R\vstartAtUnix\x88\x01\x01\x12#\n" +
	"\vend_at_unix\x18\x06 \x01(\x03H\x04R\tendAtUnix\x88\x01\x01B\a\n" +
	"\x05_slotB\r\n" +
	"\v_product_idB\a\n" +
	"\x05_sortB\x10\n" +
	"\x0e_start_at_unixB\x0e\n" +
	"\f_end_at_unix\"b\n" +
	"\x1cUpdateRecommendationResponse\x12B\n" +
	"\x0erecommendation\x18\x01 \x01(\v2\x1a.product.v1.RecommendationR\x0erecommendation\"-\n" +
	"\x1bDeleteRecommendationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\x1cDeleteRecommendationResponse2\xf5\x05\n" +
	"\x15RecommendationService\x12\x8f\x01\n" +
	"\x14CreateRecommendation\x12'.product.v1.CreateRecommendationRequest\x1a(.product.v1.CreateRecommendationResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/admin/recommendations\x12\x83\x01\n" +
	"\x13ListRecommendations\x12&.product.v1.ListRecommendationsRequest\x1a'.product.v1.ListRecommendationsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/recommendations\x12\x98\x01\n" +
	"\x18AdminListRecommendations\x12+.product.v1.AdminListRecommendationsRequest\x1a,.product.v1.AdminListRecommendationsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/admin/recommendations\x12\x94\x01\n" +
	"\x14UpdateRecommendation\x12'.product.v1.UpdateRecommendationRequest\x1a(.product.v1.UpdateRecommendationResponse\")\x82\xd3\xe4\x93\x02#:\x01*2\x1e/v1/admin/recommendations/{id}\x12\x91\x01\n" +
	"\x14DeleteRecommendation\x12'.product.v1.DeleteRecommendationRequest\x1a(.product.v1.DeleteRecommendationResponse\"&\x82\xd3\xe4\x93\x02 *\x1e/v1/admin/recommendations/{id}B1Z/github.com/tmjwjx/supermarket/api/product/v1;v1b\x06proto3"

var (
	file_product_v1_recommendation_proto_rawDescOnce sync.Once
	file_product_v1_recommendation_proto_rawDescData []byte
)

func file_product_v1_recommendation_proto_rawDescGZIP() []byte {
	file_product_v1_recommendation_proto_rawDescOnce.Do(func() {
		file_product_v1_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_v1_recommendation_proto_rawDesc), len(file_product_v1_recommendation_proto_rawDesc)))
	})
	return file_product_v1_recommendation_proto_rawDescData
}

var file_product_v1_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_product_v1_recommendation_proto_goTypes = []any{
	(*Recommendation)(nil),                   // 0: product.v1.Recommendation
	(*CreateRecommendationRequest)(nil),      // 1: product.v1.CreateRecommendationRequest
	(*CreateRecommendationResponse)(nil),     // 2: product.v1.CreateRecommendationResponse
	(*ListRecommendationsRequest)(nil),       // 3: product.v1.ListRecommendationsRequest
	(*ListRecommendationsResponse)(nil),      // 4: product.v1.ListRecommendationsResponse
	(*AdminListRecommendationsRequest)(nil),  // 5: product.v1.AdminListRecommendationsRequest
	(*AdminListRecommendationsResponse)(nil), // 6: product.v1.AdminListRecommendationsResponse
	(*UpdateRecommendationRequest)(nil),      // 7: product.v1.UpdateRecommendationRequest
	(*UpdateRecommendationResponse)(nil),     // 8: product.v1.UpdateRecommendationResponse
	(*DeleteRecommendationRequest)(nil),      // 9: product.v1.DeleteRecommendationRequest
	(*DeleteRecommendationResponse)(nil),     // 10: product.v1.DeleteRecommendationResponse
	(*ProductCard)(nil),                      // 11: product.v1.ProductCard
}
var file_product_v1_recommendation_proto_depIdxs = []int32{
	11, // 0: product.v1.Recommendation.product:type_name -> product.v1.ProductCard
	0,  // 1: product.v1.CreateRecommendationResponse.recommendation:type_name -> product.v1.Recommendation
	0,  // 2: product.v1.ListRecommendationsResponse.recommendations:type_name -> product.v1.Recommendation
	0,  // 3: product.v1.AdminListRecommendationsResponse.recommendations:type_name -> product.v1.Recommendation
	0,  // 4: product.v1.UpdateRecommendationResponse.recommendation:type_name -> product.v1.Recommendation
	1,  // 5: product.v1.RecommendationService.CreateRecommendation:input_type -> product.v1.CreateRecommendationRequest
	3,  // 6: product.v1.RecommendationService.ListRecommendations:input_type -> product.v1.ListRecommendationsRequest
	5,  // 7: product.v1.RecommendationService.AdminListRecommendations:input_type -> product.v1.AdminListRecommendationsRequest
	7,  // 8: product.v1.RecommendationService.UpdateRecommendation:input_type -> product.v1.UpdateRecommendationRequest
	9,  // 9: product.v1.RecommendationService.DeleteRecommendation:input_type -> product.v1.DeleteRecommendationRequest
	2,  // 10: product.v1.RecommendationService.CreateRecommendation:output_type -> product.v1.CreateRecommendationResponse
	4,  // 11: product.v1.RecommendationService.ListRecommendations:output_type -> product.v1.ListRecommendationsResponse
	6,  // 12: product.v1.RecommendationService.AdminListRecommendations:output_type -> product.v1.AdminListRecommendationsResponse
	8,  // 13: product.v1.RecommendationService.UpdateRecommendation:output_type -> product.v1.UpdateRecommendationResponse
	10, // 14: product.v1.RecommendationService.DeleteRecommendation:output_type -> product.v1.DeleteRecommendationResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_product_v1_recommendation_proto_init() }
func file_product_v1_recommendation_proto_init() {
	if File_product_v1_recommendation_proto != nil {
		return
	}
	file_product_v1_types_proto_init()
	file_product_v1_recommendation_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_v1_recommendation_proto_rawDesc), len(file_product_v1_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_v1_recommendation_proto_goTypes,
		DependencyIndexes: file_product_v1_recommendation_proto_depIdxs,
		MessageInfos:      file_product_v1_recommendation_proto_msgTypes,
	}.Build()
	File_product_v1_recommendation_proto = out.File
	file_product_v1_recommendation_proto_goTypes = nil
	file_product_v1_recommendation_proto_depIdxs = nil
}
