// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: product/v1/review.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationReviewServiceCreateReview = "/product.v1.ReviewService/CreateReview"
const OperationReviewServiceListProductReviews = "/product.v1.ReviewService/ListProductReviews"

type ReviewServiceHTTPServer interface {
	CreateReview(context.Context, *CreateReviewRequest) (*CreateReviewResponse, error)
	ListProductReviews(context.Context, *ListProductReviewsRequest) (*ListProductReviewsResponse, error)
}

func RegisterReviewServiceHTTPServer(s *http.Server, srv ReviewServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/reviews", _ReviewService_CreateReview0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/products/{product_id}/reviews", _ReviewService_ListProductReviews0_HTTP_Handler(srv))
}

func _ReviewService_CreateReview0_HTTP_Handler(srv ReviewServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateReviewRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReviewServiceCreateReview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateReview(ctx, req.(*CreateReviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateReviewResponse)
		return ctx.Result(200, reply)
	}
}

func _ReviewService_ListProductReviews0_HTTP_Handler(srv ReviewServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProductReviewsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReviewServiceListProductReviews)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProductReviews(ctx, req.(*ListProductReviewsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductReviewsResponse)
		return ctx.Result(200, reply)
	}
}

type ReviewServiceHTTPClient interface {
	CreateReview(ctx context.Context, req *CreateReviewRequest, opts ...http.CallOption) (rsp *CreateReviewResponse, err error)
	ListProductReviews(ctx context.Context, req *ListProductReviewsRequest, opts ...http.CallOption) (rsp *ListProductReviewsResponse, err error)
}

type ReviewServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewReviewServiceHTTPClient(client *http.Client) ReviewServiceHTTPClient {
	return &ReviewServiceHTTPClientImpl{client}
}

func (c *ReviewServiceHTTPClientImpl) CreateReview(ctx context.Context, in *CreateReviewRequest, opts ...http.CallOption) (*CreateReviewResponse, error) {
	var out CreateReviewResponse
	pattern := "/v1/reviews"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationReviewServiceCreateReview),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReviewServiceHTTPClientImpl) ListProductReviews(ctx context.Context, in *ListProductReviewsRequest, opts ...http.CallOption) (*ListProductReviewsResponse, error) {
	var out ListProductReviewsResponse
	pattern := "/v1/products/{product_id}/reviews"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationReviewServiceListProductReviews),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
