// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: product/v1/types.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MainImage     string                 `protobuf:"bytes,3,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	MinPrice      int64                  `protobuf:"varint,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MarketPrice   int64                  `protobuf:"varint,5,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	SalesCount    int64                  `protobuf:"varint,6,opt,name=sales_count,json=salesCount,proto3" json:"sales_count,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCard) Reset() {
	*x = ProductCard{}
	mi := &file_product_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCard) ProtoMessage() {}

func (x *ProductCard) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCard.ProtoReflect.Descriptor instead.
func (*ProductCard) Descriptor() ([]byte, []int) {
	return file_product_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *ProductCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCard) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *ProductCard) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ProductCard) GetMarketPrice() int64 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *ProductCard) GetSalesCount() int64 {
	if x != nil {
		return x.SalesCount
	}
	return 0
}

func (x *ProductCard) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_product_v1_types_proto protoreflect.FileDescriptor

const file_product_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x16product/v1/types.proto\x12\n" +
	"product.v1\"\xc9\x01\n" +
	"\vProductCard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"main_image\x18\x03 \x01(\tR\tmainImage\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x03R\bminPrice\x12!\n" +
	"\fmarket_price\x18\x05 \x01(\x03R\vmarketPrice\x12\x1f\n" +
	"\vsales_count\x18\x06 \x01(\x03R\n" +
	"salesCount\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06statusB1Z/github.com/tmjwjx/supermarket/api/product/v1;v1b\x06proto3"

var (
	file_product_v1_types_proto_rawDescOnce sync.Once
	file_product_v1_types_proto_rawDescData []byte
)

func file_product_v1_types_proto_rawDescGZIP() []byte {
	file_product_v1_types_proto_rawDescOnce.Do(func() {
		file_product_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_v1_types_proto_rawDesc), len(file_product_v1_types_proto_rawDesc)))
	})
	return file_product_v1_types_proto_rawDescData
}

var file_product_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_product_v1_types_proto_goTypes = []any{
	(*ProductCard)(nil), // 0: product.v1.ProductCard
}
var file_product_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_v1_types_proto_init() }
func file_product_v1_types_proto_init() {
	if File_product_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_v1_types_proto_rawDesc), len(file_product_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_v1_types_proto_goTypes,
		DependencyIndexes: file_product_v1_types_proto_depIdxs,
		MessageInfos:      file_product_v1_types_proto_msgTypes,
	}.Build()
	File_product_v1_types_proto = out.File
	file_product_v1_types_proto_goTypes = nil
	file_product_v1_types_proto_depIdxs = nil
}
