// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: user/v1/address.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAddressServiceCreateAddress = "/user.v1.AddressService/CreateAddress"
const OperationAddressServiceDeleteAddress = "/user.v1.AddressService/DeleteAddress"
const OperationAddressServiceListAddresses = "/user.v1.AddressService/ListAddresses"
const OperationAddressServiceSetDefaultAddress = "/user.v1.AddressService/SetDefaultAddress"
const OperationAddressServiceUpdateAddress = "/user.v1.AddressService/UpdateAddress"

type AddressServiceHTTPServer interface {
	CreateAddress(context.Context, *CreateAddressRequest) (*CreateAddressResponse, error)
	DeleteAddress(context.Context, *DeleteAddressRequest) (*DeleteAddressResponse, error)
	ListAddresses(context.Context, *ListAddressesRequest) (*ListAddressesResponse, error)
	SetDefaultAddress(context.Context, *SetDefaultAddressRequest) (*SetDefaultAddressResponse, error)
	UpdateAddress(context.Context, *UpdateAddressRequest) (*UpdateAddressResponse, error)
}

func RegisterAddressServiceHTTPServer(s *http.Server, srv AddressServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/addresses", _AddressService_CreateAddress0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/addresses", _AddressService_ListAddresses0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/addresses/{id}", _AddressService_DeleteAddress0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/addresses/{id}", _AddressService_UpdateAddress0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/addresses/{id}:default", _AddressService_SetDefaultAddress0_HTTP_Handler(srv))
}

func _AddressService_CreateAddress0_HTTP_Handler(srv AddressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAddressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAddressServiceCreateAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAddress(ctx, req.(*CreateAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAddressResponse)
		return ctx.Result(200, reply)
	}
}

func _AddressService_ListAddresses0_HTTP_Handler(srv AddressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAddressesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAddressServiceListAddresses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAddresses(ctx, req.(*ListAddressesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAddressesResponse)
		return ctx.Result(200, reply)
	}
}

func _AddressService_DeleteAddress0_HTTP_Handler(srv AddressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAddressRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAddressServiceDeleteAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAddress(ctx, req.(*DeleteAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteAddressResponse)
		return ctx.Result(200, reply)
	}
}

func _AddressService_UpdateAddress0_HTTP_Handler(srv AddressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAddressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAddressServiceUpdateAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAddress(ctx, req.(*UpdateAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateAddressResponse)
		return ctx.Result(200, reply)
	}
}

func _AddressService_SetDefaultAddress0_HTTP_Handler(srv AddressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetDefaultAddressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAddressServiceSetDefaultAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetDefaultAddress(ctx, req.(*SetDefaultAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetDefaultAddressResponse)
		return ctx.Result(200, reply)
	}
}

type AddressServiceHTTPClient interface {
	CreateAddress(ctx context.Context, req *CreateAddressRequest, opts ...http.CallOption) (rsp *CreateAddressResponse, err error)
	DeleteAddress(ctx context.Context, req *DeleteAddressRequest, opts ...http.CallOption) (rsp *DeleteAddressResponse, err error)
	ListAddresses(ctx context.Context, req *ListAddressesRequest, opts ...http.CallOption) (rsp *ListAddressesResponse, err error)
	SetDefaultAddress(ctx context.Context, req *SetDefaultAddressRequest, opts ...http.CallOption) (rsp *SetDefaultAddressResponse, err error)
	UpdateAddress(ctx context.Context, req *UpdateAddressRequest, opts ...http.CallOption) (rsp *UpdateAddressResponse, err error)
}

type AddressServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAddressServiceHTTPClient(client *http.Client) AddressServiceHTTPClient {
	return &AddressServiceHTTPClientImpl{client}
}

func (c *AddressServiceHTTPClientImpl) CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...http.CallOption) (*CreateAddressResponse, error) {
	var out CreateAddressResponse
	pattern := "/v1/addresses"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAddressServiceCreateAddress),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AddressServiceHTTPClientImpl) DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...http.CallOption) (*DeleteAddressResponse, error) {
	var out DeleteAddressResponse
	pattern := "/v1/addresses/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAddressServiceDeleteAddress),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AddressServiceHTTPClientImpl) ListAddresses(ctx context.Context, in *ListAddressesRequest, opts ...http.CallOption) (*ListAddressesResponse, error) {
	var out ListAddressesResponse
	pattern := "/v1/addresses"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAddressServiceListAddresses),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AddressServiceHTTPClientImpl) SetDefaultAddress(ctx context.Context, in *SetDefaultAddressRequest, opts ...http.CallOption) (*SetDefaultAddressResponse, error) {
	var out SetDefaultAddressResponse
	pattern := "/v1/addresses/{id}:default"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAddressServiceSetDefaultAddress),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AddressServiceHTTPClientImpl) UpdateAddress(ctx context.Context, in *UpdateAddressRequest, opts ...http.CallOption) (*UpdateAddressResponse, error) {
	var out UpdateAddressResponse
	pattern := "/v1/addresses/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAddressServiceUpdateAddress),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
