// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ADMIN_UNSPECIFIED         ErrorReason = 0
	ErrorReason_ADMIN_INVALID_CREDENTIALS ErrorReason = 1
	ErrorReason_ADMIN_DISABLED            ErrorReason = 2
	ErrorReason_ADMIN_INVALID_ARGUMENT    ErrorReason = 3
	ErrorReason_ADMIN_FORBIDDEN           ErrorReason = 4
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ADMIN_UNSPECIFIED",
		1: "ADMIN_INVALID_CREDENTIALS",
		2: "ADMIN_DISABLED",
		3: "ADMIN_INVALID_ARGUMENT",
		4: "ADMIN_FORBIDDEN",
	}
	ErrorReason_value = map[string]int32{
		"ADMIN_UNSPECIFIED":         0,
		"ADMIN_INVALID_CREDENTIALS": 1,
		"ADMIN_DISABLED":            2,
		"ADMIN_INVALID_ARGUMENT":    3,
		"ADMIN_FORBIDDEN":           4,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_admin_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_admin_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_admin_v1_error_reason_proto protoreflect.FileDescriptor

const file_admin_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1badmin/v1/error_reason.proto\x12\badmin.v1*\x88\x01\n" +
	"\vErrorReason\x12\x15\n" +
	"\x11ADMIN_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ADMIN_INVALID_CREDENTIALS\x10\x01\x12\x12\n" +
	"\x0eADMIN_DISABLED\x10\x02\x12\x1a\n" +
	"\x16ADMIN_INVALID_ARGUMENT\x10\x03\x12\x13\n" +
	"\x0fADMIN_FORBIDDEN\x10\x04B/Z-github.com/tmjwjx/supermarket/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_error_reason_proto_rawDescOnce sync.Once
	file_admin_v1_error_reason_proto_rawDescData []byte
)

func file_admin_v1_error_reason_proto_rawDescGZIP() []byte {
	file_admin_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_admin_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_error_reason_proto_rawDesc), len(file_admin_v1_error_reason_proto_rawDesc)))
	})
	return file_admin_v1_error_reason_proto_rawDescData
}

var file_admin_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: admin.v1.ErrorReason
}
var file_admin_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_v1_error_reason_proto_init() }
func file_admin_v1_error_reason_proto_init() {
	if File_admin_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_error_reason_proto_rawDesc), len(file_admin_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_admin_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_admin_v1_error_reason_proto_enumTypes,
	}.Build()
	File_admin_v1_error_reason_proto = out.File
	file_admin_v1_error_reason_proto_goTypes = nil
	file_admin_v1_error_reason_proto_depIdxs = nil
}
