// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/tmjwjx/supermarket/app/payment/internal/conf"
	"github.com/tmjwjx/supermarket/app/payment/internal/server"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, logger *slog.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer)
	httpServer := server.NewHTTPServer(confServer)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
