// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inventory/v1/stock.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	OnHand        int64                  `protobuf:"varint,2,opt,name=on_hand,json=onHand,proto3" json:"on_hand,omitempty"`
	Reserved      int64                  `protobuf:"varint,3,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Available     int64                  `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_inventory_v1_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{0}
}

func (x *Stock) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *Stock) GetOnHand() int64 {
	if x != nil {
		return x.OnHand
	}
	return 0
}

func (x *Stock) GetReserved() int64 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *Stock) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

type StockItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_inventory_v1_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{1}
}

func (x *StockItem) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *StockItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStockRequest) Reset() {
	*x = CreateStockRequest{}
	mi := &file_inventory_v1_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockRequest) ProtoMessage() {}

func (x *CreateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockRequest.ProtoReflect.Descriptor instead.
func (*CreateStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStockRequest) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

type CreateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStockResponse) Reset() {
	*x = CreateStockResponse{}
	mi := &file_inventory_v1_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockResponse) ProtoMessage() {}

func (x *CreateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockResponse.ProtoReflect.Descriptor instead.
func (*CreateStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{3}
}

func (x *CreateStockResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type AdjustStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustStockRequest) Reset() {
	*x = AdjustStockRequest{}
	mi := &file_inventory_v1_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustStockRequest) ProtoMessage() {}

func (x *AdjustStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustStockRequest.ProtoReflect.Descriptor instead.
func (*AdjustStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{4}
}

func (x *AdjustStockRequest) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *AdjustStockRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *AdjustStockRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AdjustStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustStockResponse) Reset() {
	*x = AdjustStockResponse{}
	mi := &file_inventory_v1_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustStockResponse) ProtoMessage() {}

func (x *AdjustStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustStockResponse.ProtoReflect.Descriptor instead.
func (*AdjustStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{5}
}

func (x *AdjustStockResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type GetStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuIds        []string               `protobuf:"bytes,1,rep,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStocksRequest) Reset() {
	*x = GetStocksRequest{}
	mi := &file_inventory_v1_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStocksRequest) ProtoMessage() {}

func (x *GetStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStocksRequest.ProtoReflect.Descriptor instead.
func (*GetStocksRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{6}
}

func (x *GetStocksRequest) GetSkuIds() []string {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

type GetStocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        []*Stock               `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStocksResponse) Reset() {
	*x = GetStocksResponse{}
	mi := &file_inventory_v1_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStocksResponse) ProtoMessage() {}

func (x *GetStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStocksResponse.ProtoReflect.Descriptor instead.
func (*GetStocksResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{7}
}

func (x *GetStocksResponse) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type AdminGetStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuIds        []string               `protobuf:"bytes,1,rep,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetStocksRequest) Reset() {
	*x = AdminGetStocksRequest{}
	mi := &file_inventory_v1_stock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetStocksRequest) ProtoMessage() {}

func (x *AdminGetStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetStocksRequest.ProtoReflect.Descriptor instead.
func (*AdminGetStocksRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{8}
}

func (x *AdminGetStocksRequest) GetSkuIds() []string {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

type AdminGetStocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        []*Stock               `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminGetStocksResponse) Reset() {
	*x = AdminGetStocksResponse{}
	mi := &file_inventory_v1_stock_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetStocksResponse) ProtoMessage() {}

func (x *AdminGetStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetStocksResponse.ProtoReflect.Descriptor instead.
func (*AdminGetStocksResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{9}
}

func (x *AdminGetStocksResponse) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

type ReserveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*StockItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ExpireUnix    int64                  `protobuf:"varint,3,opt,name=expire_unix,json=expireUnix,proto3" json:"expire_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_inventory_v1_stock_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{10}
}

func (x *ReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStockRequest) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveStockRequest) GetExpireUnix() int64 {
	if x != nil {
		return x.ExpireUnix
	}
	return 0
}

type ReserveStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_inventory_v1_stock_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{11}
}

type ConfirmReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationRequest) Reset() {
	*x = ConfirmReservationRequest{}
	mi := &file_inventory_v1_stock_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationRequest) ProtoMessage() {}

func (x *ConfirmReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmReservationRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmReservationRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ConfirmReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationResponse) Reset() {
	*x = ConfirmReservationResponse{}
	mi := &file_inventory_v1_stock_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationResponse) ProtoMessage() {}

func (x *ConfirmReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmReservationResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{13}
}

type ReleaseReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_inventory_v1_stock_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{14}
}

func (x *ReleaseReservationRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ReleaseReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationResponse) Reset() {
	*x = ReleaseReservationResponse{}
	mi := &file_inventory_v1_stock_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationResponse) ProtoMessage() {}

func (x *ReleaseReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_stock_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservationResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_stock_proto_rawDescGZIP(), []int{15}
}

var File_inventory_v1_stock_proto protoreflect.FileDescriptor

const file_inventory_v1_stock_proto_rawDesc = "" +
	"\n" +
	"\x18inventory/v1/stock.proto\x12\finventory.v1\x1a\x1cgoogle/api/annotations.proto\"q\n" +
	"\x05Stock\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12\x17\n" +
	"\aon_hand\x18\x02 \x01(\x03R\x06onHand\x12\x1a\n" +
	"\breserved\x18\x03 \x01(\x03R\breserved\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\x03R\tavailable\">\n" +
	"\tStockItem\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"+\n" +
	"\x12CreateStockRequest\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\"@\n" +
	"\x13CreateStockResponse\x12)\n" +
	"\x05stock\x18\x01 \x01(\v2\x13.inventory.v1.StockR\x05stock\"Y\n" +
	"\x12AdjustStockRequest\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"@\n" +
	"\x13AdjustStockResponse\x12)\n" +
	"\x05stock\x18\x01 \x01(\v2\x13.inventory.v1.StockR\x05stock\"+\n" +
	"\x10GetStocksRequest\x12\x17\n" +
	"\asku_ids\x18\x01 \x03(\tR\x06skuIds\"@\n" +
	"\x11GetStocksResponse\x12+\n" +
	"\x06stocks\x18\x01 \x03(\v2\x13.inventory.v1.StockR\x06stocks\"0\n" +
	"\x15AdminGetStocksRequest\x12\x17\n" +
	"\asku_ids\x18\x01 \x03(\tR\x06skuIds\"E\n" +
	"\x16AdminGetStocksResponse\x12+\n" +
	"\x06stocks\x18\x01 \x03(\v2\x13.inventory.v1.StockR\x06stocks\"\x80\x01\n" +
	"\x13ReserveStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.inventory.v1.StockItemR\x05items\x12\x1f\n" +
	"\vexpire_unix\x18\x03 \x01(\x03R\n" +
	"expireUnix\"\x16\n" +
	"\x14ReserveStockResponse\"6\n" +
	"\x19ConfirmReservationRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x1c\n" +
	"\x1aConfirmReservationResponse\"6\n" +
	"\x19ReleaseReservationRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x1c\n" +
	"\x1aReleaseReservationResponse2\xdc\x05\n" +
	"\fStockService\x12R\n" +
	"\vCreateStock\x12 .inventory.v1.CreateStockRequest\x1a!.inventory.v1.CreateStockResponse\x12v\n" +
	"\vAdjustStock\x12 .inventory.v1.AdjustStockRequest\x1a!.inventory.v1.AdjustStockResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/admin/stocks:adjust\x12`\n" +
	"\tGetStocks\x12\x1e.inventory.v1.GetStocksRequest\x1a\x1f.inventory.v1.GetStocksResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/stocks\x12u\n" +
	"\x0eAdminGetStocks\x12#.inventory.v1.AdminGetStocksRequest\x1a$.inventory.v1.AdminGetStocksResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/admin/stocks\x12U\n" +
	"\fReserveStock\x12!.inventory.v1.ReserveStockRequest\x1a\".inventory.v1.ReserveStockResponse\x12g\n" +
	"\x12ConfirmReservation\x12'.inventory.v1.ConfirmReservationRequest\x1a(.inventory.v1.ConfirmReservationResponse\x12g\n" +
	"\x12ReleaseReservation\x12'.inventory.v1.ReleaseReservationRequest\x1a(.inventory.v1.ReleaseReservationResponseB3Z1github.com/tmjwjx/supermarket/api/inventory/v1;v1b\x06proto3"

var (
	file_inventory_v1_stock_proto_rawDescOnce sync.Once
	file_inventory_v1_stock_proto_rawDescData []byte
)

func file_inventory_v1_stock_proto_rawDescGZIP() []byte {
	file_inventory_v1_stock_proto_rawDescOnce.Do(func() {
		file_inventory_v1_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_stock_proto_rawDesc), len(file_inventory_v1_stock_proto_rawDesc)))
	})
	return file_inventory_v1_stock_proto_rawDescData
}

var file_inventory_v1_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_inventory_v1_stock_proto_goTypes = []any{
	(*Stock)(nil),                      // 0: inventory.v1.Stock
	(*StockItem)(nil),                  // 1: inventory.v1.StockItem
	(*CreateStockRequest)(nil),         // 2: inventory.v1.CreateStockRequest
	(*CreateStockResponse)(nil),        // 3: inventory.v1.CreateStockResponse
	(*AdjustStockRequest)(nil),         // 4: inventory.v1.AdjustStockRequest
	(*AdjustStockResponse)(nil),        // 5: inventory.v1.AdjustStockResponse
	(*GetStocksRequest)(nil),           // 6: inventory.v1.GetStocksRequest
	(*GetStocksResponse)(nil),          // 7: inventory.v1.GetStocksResponse
	(*AdminGetStocksRequest)(nil),      // 8: inventory.v1.AdminGetStocksRequest
	(*AdminGetStocksResponse)(nil),     // 9: inventory.v1.AdminGetStocksResponse
	(*ReserveStockRequest)(nil),        // 10: inventory.v1.ReserveStockRequest
	(*ReserveStockResponse)(nil),       // 11: inventory.v1.ReserveStockResponse
	(*ConfirmReservationRequest)(nil),  // 12: inventory.v1.ConfirmReservationRequest
	(*ConfirmReservationResponse)(nil), // 13: inventory.v1.ConfirmReservationResponse
	(*ReleaseReservationRequest)(nil),  // 14: inventory.v1.ReleaseReservationRequest
	(*ReleaseReservationResponse)(nil), // 15: inventory.v1.ReleaseReservationResponse
}
var file_inventory_v1_stock_proto_depIdxs = []int32{
	0,  // 0: inventory.v1.CreateStockResponse.stock:type_name -> inventory.v1.Stock
	0,  // 1: inventory.v1.AdjustStockResponse.stock:type_name -> inventory.v1.Stock
	0,  // 2: inventory.v1.GetStocksResponse.stocks:type_name -> inventory.v1.Stock
	0,  // 3: inventory.v1.AdminGetStocksResponse.stocks:type_name -> inventory.v1.Stock
	1,  // 4: inventory.v1.ReserveStockRequest.items:type_name -> inventory.v1.StockItem
	2,  // 5: inventory.v1.StockService.CreateStock:input_type -> inventory.v1.CreateStockRequest
	4,  // 6: inventory.v1.StockService.AdjustStock:input_type -> inventory.v1.AdjustStockRequest
	6,  // 7: inventory.v1.StockService.GetStocks:input_type -> inventory.v1.GetStocksRequest
	8,  // 8: inventory.v1.StockService.AdminGetStocks:input_type -> inventory.v1.AdminGetStocksRequest
	10, // 9: inventory.v1.StockService.ReserveStock:input_type -> inventory.v1.ReserveStockRequest
	12, // 10: inventory.v1.StockService.ConfirmReservation:input_type -> inventory.v1.ConfirmReservationRequest
	14, // 11: inventory.v1.StockService.ReleaseReservation:input_type -> inventory.v1.ReleaseReservationRequest
	3,  // 12: inventory.v1.StockService.CreateStock:output_type -> inventory.v1.CreateStockResponse
	5,  // 13: inventory.v1.StockService.AdjustStock:output_type -> inventory.v1.AdjustStockResponse
	7,  // 14: inventory.v1.StockService.GetStocks:output_type -> inventory.v1.GetStocksResponse
	9,  // 15: inventory.v1.StockService.AdminGetStocks:output_type -> inventory.v1.AdminGetStocksResponse
	11, // 16: inventory.v1.StockService.ReserveStock:output_type -> inventory.v1.ReserveStockResponse
	13, // 17: inventory.v1.StockService.ConfirmReservation:output_type -> inventory.v1.ConfirmReservationResponse
	15, // 18: inventory.v1.StockService.ReleaseReservation:output_type -> inventory.v1.ReleaseReservationResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_inventory_v1_stock_proto_init() }
func file_inventory_v1_stock_proto_init() {
	if File_inventory_v1_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_stock_proto_rawDesc), len(file_inventory_v1_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_stock_proto_goTypes,
		DependencyIndexes: file_inventory_v1_stock_proto_depIdxs,
		MessageInfos:      file_inventory_v1_stock_proto_msgTypes,
	}.Build()
	File_inventory_v1_stock_proto = out.File
	file_inventory_v1_stock_proto_goTypes = nil
	file_inventory_v1_stock_proto_depIdxs = nil
}
