// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: inventory/v1/stock.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationStockServiceAdjustStock = "/inventory.v1.StockService/AdjustStock"
const OperationStockServiceAdminGetStocks = "/inventory.v1.StockService/AdminGetStocks"
const OperationStockServiceGetStocks = "/inventory.v1.StockService/GetStocks"

type StockServiceHTTPServer interface {
	AdjustStock(context.Context, *AdjustStockRequest) (*AdjustStockResponse, error)
	AdminGetStocks(context.Context, *AdminGetStocksRequest) (*AdminGetStocksResponse, error)
	GetStocks(context.Context, *GetStocksRequest) (*GetStocksResponse, error)
}

func RegisterStockServiceHTTPServer(s *http.Server, srv StockServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/admin/stocks:adjust", _StockService_AdjustStock0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/stocks", _StockService_GetStocks0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/stocks", _StockService_AdminGetStocks0_HTTP_Handler(srv))
}

func _StockService_AdjustStock0_HTTP_Handler(srv StockServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdjustStockRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStockServiceAdjustStock)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdjustStock(ctx, req.(*AdjustStockRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdjustStockResponse)
		return ctx.Result(200, reply)
	}
}

func _StockService_GetStocks0_HTTP_Handler(srv StockServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStocksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStockServiceGetStocks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStocks(ctx, req.(*GetStocksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetStocksResponse)
		return ctx.Result(200, reply)
	}
}

func _StockService_AdminGetStocks0_HTTP_Handler(srv StockServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminGetStocksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStockServiceAdminGetStocks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminGetStocks(ctx, req.(*AdminGetStocksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminGetStocksResponse)
		return ctx.Result(200, reply)
	}
}

type StockServiceHTTPClient interface {
	AdjustStock(ctx context.Context, req *AdjustStockRequest, opts ...http.CallOption) (rsp *AdjustStockResponse, err error)
	AdminGetStocks(ctx context.Context, req *AdminGetStocksRequest, opts ...http.CallOption) (rsp *AdminGetStocksResponse, err error)
	GetStocks(ctx context.Context, req *GetStocksRequest, opts ...http.CallOption) (rsp *GetStocksResponse, err error)
}

type StockServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStockServiceHTTPClient(client *http.Client) StockServiceHTTPClient {
	return &StockServiceHTTPClientImpl{client}
}

func (c *StockServiceHTTPClientImpl) AdjustStock(ctx context.Context, in *AdjustStockRequest, opts ...http.CallOption) (*AdjustStockResponse, error) {
	var out AdjustStockResponse
	pattern := "/v1/admin/stocks:adjust"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationStockServiceAdjustStock),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StockServiceHTTPClientImpl) AdminGetStocks(ctx context.Context, in *AdminGetStocksRequest, opts ...http.CallOption) (*AdminGetStocksResponse, error) {
	var out AdminGetStocksResponse
	pattern := "/v1/admin/stocks"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationStockServiceAdminGetStocks),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *StockServiceHTTPClientImpl) GetStocks(ctx context.Context, in *GetStocksRequest, opts ...http.CallOption) (*GetStocksResponse, error) {
	var out GetStocksResponse
	pattern := "/v1/stocks"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationStockServiceGetStocks),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
