// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: order/v1/order.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationCartServiceAddCartItem = "/order.v1.CartService/AddCartItem"
const OperationCartServiceListCartItems = "/order.v1.CartService/ListCartItems"
const OperationCartServiceRemoveCartItems = "/order.v1.CartService/RemoveCartItems"
const OperationCartServiceUpdateCartItem = "/order.v1.CartService/UpdateCartItem"

type CartServiceHTTPServer interface {
	AddCartItem(context.Context, *AddCartItemRequest) (*AddCartItemResponse, error)
	ListCartItems(context.Context, *ListCartItemsRequest) (*ListCartItemsResponse, error)
	RemoveCartItems(context.Context, *RemoveCartItemsRequest) (*RemoveCartItemsResponse, error)
	UpdateCartItem(context.Context, *UpdateCartItemRequest) (*UpdateCartItemResponse, error)
}

func RegisterCartServiceHTTPServer(s *http.Server, srv CartServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/cart/items", _CartService_AddCartItem0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/cart/items/{sku_id}", _CartService_UpdateCartItem0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/cart/items", _CartService_ListCartItems0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/cart/items:batchDelete", _CartService_RemoveCartItems0_HTTP_Handler(srv))
}

func _CartService_AddCartItem0_HTTP_Handler(srv CartServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddCartItemRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCartServiceAddCartItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddCartItem(ctx, req.(*AddCartItemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddCartItemResponse)
		return ctx.Result(200, reply)
	}
}

func _CartService_UpdateCartItem0_HTTP_Handler(srv CartServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCartItemRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCartServiceUpdateCartItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCartItem(ctx, req.(*UpdateCartItemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCartItemResponse)
		return ctx.Result(200, reply)
	}
}

func _CartService_ListCartItems0_HTTP_Handler(srv CartServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCartItemsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCartServiceListCartItems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCartItems(ctx, req.(*ListCartItemsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCartItemsResponse)
		return ctx.Result(200, reply)
	}
}

func _CartService_RemoveCartItems0_HTTP_Handler(srv CartServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveCartItemsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCartServiceRemoveCartItems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveCartItems(ctx, req.(*RemoveCartItemsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveCartItemsResponse)
		return ctx.Result(200, reply)
	}
}

type CartServiceHTTPClient interface {
	AddCartItem(ctx context.Context, req *AddCartItemRequest, opts ...http.CallOption) (rsp *AddCartItemResponse, err error)
	ListCartItems(ctx context.Context, req *ListCartItemsRequest, opts ...http.CallOption) (rsp *ListCartItemsResponse, err error)
	RemoveCartItems(ctx context.Context, req *RemoveCartItemsRequest, opts ...http.CallOption) (rsp *RemoveCartItemsResponse, err error)
	UpdateCartItem(ctx context.Context, req *UpdateCartItemRequest, opts ...http.CallOption) (rsp *UpdateCartItemResponse, err error)
}

type CartServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCartServiceHTTPClient(client *http.Client) CartServiceHTTPClient {
	return &CartServiceHTTPClientImpl{client}
}

func (c *CartServiceHTTPClientImpl) AddCartItem(ctx context.Context, in *AddCartItemRequest, opts ...http.CallOption) (*AddCartItemResponse, error) {
	var out AddCartItemResponse
	pattern := "/v1/cart/items"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCartServiceAddCartItem),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CartServiceHTTPClientImpl) ListCartItems(ctx context.Context, in *ListCartItemsRequest, opts ...http.CallOption) (*ListCartItemsResponse, error) {
	var out ListCartItemsResponse
	pattern := "/v1/cart/items"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCartServiceListCartItems),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CartServiceHTTPClientImpl) RemoveCartItems(ctx context.Context, in *RemoveCartItemsRequest, opts ...http.CallOption) (*RemoveCartItemsResponse, error) {
	var out RemoveCartItemsResponse
	pattern := "/v1/cart/items:batchDelete"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCartServiceRemoveCartItems),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CartServiceHTTPClientImpl) UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, opts ...http.CallOption) (*UpdateCartItemResponse, error) {
	var out UpdateCartItemResponse
	pattern := "/v1/cart/items/{sku_id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCartServiceUpdateCartItem),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationOrderServiceAdminListOrders = "/order.v1.OrderService/AdminListOrders"
const OperationOrderServiceAdminShipOrder = "/order.v1.OrderService/AdminShipOrder"
const OperationOrderServiceCancelOrder = "/order.v1.OrderService/CancelOrder"
const OperationOrderServiceConfirmOrder = "/order.v1.OrderService/ConfirmOrder"
const OperationOrderServiceCreateOrder = "/order.v1.OrderService/CreateOrder"
const OperationOrderServiceGetOrder = "/order.v1.OrderService/GetOrder"
const OperationOrderServiceListOrders = "/order.v1.OrderService/ListOrders"

type OrderServiceHTTPServer interface {
	AdminListOrders(context.Context, *AdminListOrdersRequest) (*AdminListOrdersResponse, error)
	AdminShipOrder(context.Context, *AdminShipOrderRequest) (*AdminShipOrderResponse, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	ConfirmOrder(context.Context, *ConfirmOrderRequest) (*ConfirmOrderResponse, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
}

func RegisterOrderServiceHTTPServer(s *http.Server, srv OrderServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/orders", _OrderService_CreateOrder0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/orders", _OrderService_ListOrders0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/orders/{id}", _OrderService_GetOrder0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/orders/{id}:cancel", _OrderService_CancelOrder0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/orders/{id}:confirm", _OrderService_ConfirmOrder0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin/orders", _OrderService_AdminListOrders0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin/orders/{id}:ship", _OrderService_AdminShipOrder0_HTTP_Handler(srv))
}

func _OrderService_CreateOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceCreateOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOrder(ctx, req.(*CreateOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateOrderResponse)
		return ctx.Result(200, reply)
	}
}

func _OrderService_ListOrders0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceListOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOrders(ctx, req.(*ListOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOrdersResponse)
		return ctx.Result(200, reply)
	}
}

func _OrderService_GetOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceGetOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrder(ctx, req.(*GetOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetOrderResponse)
		return ctx.Result(200, reply)
	}
}

func _OrderService_CancelOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceCancelOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelOrder(ctx, req.(*CancelOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelOrderResponse)
		return ctx.Result(200, reply)
	}
}

func _OrderService_ConfirmOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfirmOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceConfirmOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConfirmOrder(ctx, req.(*ConfirmOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConfirmOrderResponse)
		return ctx.Result(200, reply)
	}
}

func _OrderService_AdminListOrders0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminListOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceAdminListOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminListOrders(ctx, req.(*AdminListOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminListOrdersResponse)
		return ctx.Result(200, reply)
	}
}

func _OrderService_AdminShipOrder0_HTTP_Handler(srv OrderServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AdminShipOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderServiceAdminShipOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AdminShipOrder(ctx, req.(*AdminShipOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminShipOrderResponse)
		return ctx.Result(200, reply)
	}
}

type OrderServiceHTTPClient interface {
	AdminListOrders(ctx context.Context, req *AdminListOrdersRequest, opts ...http.CallOption) (rsp *AdminListOrdersResponse, err error)
	AdminShipOrder(ctx context.Context, req *AdminShipOrderRequest, opts ...http.CallOption) (rsp *AdminShipOrderResponse, err error)
	CancelOrder(ctx context.Context, req *CancelOrderRequest, opts ...http.CallOption) (rsp *CancelOrderResponse, err error)
	ConfirmOrder(ctx context.Context, req *ConfirmOrderRequest, opts ...http.CallOption) (rsp *ConfirmOrderResponse, err error)
	CreateOrder(ctx context.Context, req *CreateOrderRequest, opts ...http.CallOption) (rsp *CreateOrderResponse, err error)
	GetOrder(ctx context.Context, req *GetOrderRequest, opts ...http.CallOption) (rsp *GetOrderResponse, err error)
	ListOrders(ctx context.Context, req *ListOrdersRequest, opts ...http.CallOption) (rsp *ListOrdersResponse, err error)
}

type OrderServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderServiceHTTPClient(client *http.Client) OrderServiceHTTPClient {
	return &OrderServiceHTTPClientImpl{client}
}

func (c *OrderServiceHTTPClientImpl) AdminListOrders(ctx context.Context, in *AdminListOrdersRequest, opts ...http.CallOption) (*AdminListOrdersResponse, error) {
	var out AdminListOrdersResponse
	pattern := "/v1/admin/orders"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrderServiceAdminListOrders),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) AdminShipOrder(ctx context.Context, in *AdminShipOrderRequest, opts ...http.CallOption) (*AdminShipOrderResponse, error) {
	var out AdminShipOrderResponse
	pattern := "/v1/admin/orders/{id}:ship"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrderServiceAdminShipOrder),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...http.CallOption) (*CancelOrderResponse, error) {
	var out CancelOrderResponse
	pattern := "/v1/orders/{id}:cancel"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrderServiceCancelOrder),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) ConfirmOrder(ctx context.Context, in *ConfirmOrderRequest, opts ...http.CallOption) (*ConfirmOrderResponse, error) {
	var out ConfirmOrderResponse
	pattern := "/v1/orders/{id}:confirm"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrderServiceConfirmOrder),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...http.CallOption) (*CreateOrderResponse, error) {
	var out CreateOrderResponse
	pattern := "/v1/orders"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrderServiceCreateOrder),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...http.CallOption) (*GetOrderResponse, error) {
	var out GetOrderResponse
	pattern := "/v1/orders/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrderServiceGetOrder),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OrderServiceHTTPClientImpl) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...http.CallOption) (*ListOrdersResponse, error) {
	var out ListOrdersResponse
	pattern := "/v1/orders"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrderServiceListOrders),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
