server:
  http:
    addr: 0.0.0.0:8006
    timeout_ms: 1000
  grpc:
    addr: 0.0.0.0:9006
    timeout_ms: 1000
data:
  database:
    driver: mysql
    source: "root:root@tcp(mysql:3306)/admin?timeout=5s&parseTime=True&loc=Local&charset=utf8mb4"
    debug: true
    auto_migrate: true
auth:
  jwt_secret: tmjwjx-admin-jwt-secret
  token_expire_ms: 43200000
