server:
  http:
    addr: 0.0.0.0:8080
    timeout_ms: 7000
client:
  user:
    addr: 127.0.0.1:9000
    timeout_ms: 1000
  product:
    addr: 127.0.0.1:9001
    timeout_ms: 1000
  inventory:
    addr: 127.0.0.1:9002
    timeout_ms: 1000
  order:
    addr: 127.0.0.1:9003
    timeout_ms: 6000
  payment:
    addr: 127.0.0.1:9004
    timeout_ms: 1000
  notification:
    addr: 127.0.0.1:9005
    timeout_ms: 1000
  admin:
    addr: 127.0.0.1:9006
    timeout_ms: 1000
auth:
  jwt_secret: ${AUTH_JWT_SECRET:change-me-local-jwt-secret}
  admin_jwt_secret: ${ADMIN_JWT_SECRET:change-me-admin-jwt-secret}
